### ISSUE TITLE
Icon colors change to black when click on FluentNavLink occurs

### ISSUE THREAD

**Issue by woha** [microsoft/fluentui-blazor#1065] opened 2023-12-04 15:20 UTC
I'm using `FluentIcon` with `Color` property set to `Color.Warning` (`<FluentIcon Value="@(new Icons.Regular.Size24.Bookmark())" Color="Color.Warning" />`).
The color is correctly displayed - initially, but after clicking on a `FluentNavLink` it changes to black.

![2023-12-04_16-15-46](https://github.com/microsoft/fluentui-blazor/assets/17140559/aa56db74-ebc4-4a33-8fb4-a034ec11f81e)

See demo code here: https://github.com/woha/icon-color-demo

**Comment by dvoituron** [comment] 2023-12-04 15:52
The problem is with the `variables.css` file.
I don't know (yet) why the `variables.css` file is unloaded when you click on another element.
We'll look into it and come up with a fix for the next release.

In the meantime, you can add this style to the `MainLayout.razor` file to fix the problem.

```html
@inherits LayoutComponentBase
<style>
    :root {
        --font-monospace: Consolas, "Courier New", "Liberation Mono", SFMono-Regular, Menlo, Monaco, monospace;
        --success: #0E700E;
        --warning: #E9835E;
        --error: #BC2F32;
        --info: #616161;
        --presence-available: #13a10e;
        --presence-away: #eaa300;
        --presence-busy: #d13438;
        --presence-dnd: #d13438;
        --presence-offline: #adadad;
        --presence-oof: #c239b3;
        --presence-unknown: #d13438;
        --highlight-bg: #fff3cd;
    }
</style>
<FluentLayout>
   ...
</FluentLayout>
```

**Comment by woha** [comment] 2023-12-04 16:07
Thank you @dvoituron, I will try your fix.

**Comment by vnbaaij** [comment] 2023-12-07 13:17
I ran your porject together with the in development version of the library (4.2) were we are using a different way of loading the `variables.css` data and the problem is not present there anymore:
![issue-#1065](https://github.com/microsoft/fluentui-blazor/assets/1761079/31553668-1506-48db-8bbb-e78add8bded6)

Closing this as it will be fixed with this next release

**Closed by vnbaaij** 2023-12-07 13:17 UTC
