### ISSUE TITLE
fix: FluentPopup can get hidden behind splitter

### ISSUE THREAD

**Issue by adamint** [microsoft/fluentui-blazor#2490] opened 2024-08-07 16:27 UTC
# 🐛 Bug Report

We noticed in https://github.com/dotnet/aspire/pull/5018#issuecomment-2259424320 that a fluent popup can get hidden under a fluent splitter. This shouldn't be the case, as popups should appear above all content.

## 💻 Repro or Code Sample
https://github.com/dotnet/aspire/tree/fd2dc694a3d073593b539330cb5bbdd37b0afdb2/src/Aspire.Dashboard

Run dashboard, open detail view, open the popup on gridvalues.

## 🤔 Expected Behavior
Popup appears in its entirety.

## 😯 Current Behavior
Some appears under the splitter bar/other panel.

## 🌍 Your Environment

* OS & Device: [e.g. **MacOS**, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. **Microsoft Edge**, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [8.0.3 and 4.9.3]

**Comment by JamesNK** [comment] 2024-08-09 13:57
The issue is visible on the branch of the linked PR: https://github.com/adamint/aspire/tree/dev/adamint/4412-multiline-string-view

**Comment by dvoituron** [comment] 2024-08-09 14:34
I have found a way to reproduce this problem.
This seems similar to a previous issue about tooltips where we needed to add a `FluentTooltipProvider`.

The reason is that the `fluent-menu` component is created inside a DIV component, which prevents external rendering.
There is no simple, immediate solution. 
So we will add another provider `FluentMenuProvider` to solve this. I can work on this in the next few days.

**Comment by dvoituron** [comment] 2024-08-10 16:36
This issue will be fixed with this new PR #2510.
Once this PR has been approved and merged with `dev` you can immediately test your code using the Preview flow.

https://github.com/microsoft/fluentui-blazor/blob/dev/docs/using-latest-daily.md

**Comment by emetrix** [comment] 2024-08-15 08:37
Hi Denis,
do you think this fix may also affect #2029 ?

![image](https://github.com/user-attachments/assets/db69f7de-f6f0-479e-95a2-084036cb3466)

**Comment by dvoituron** [comment] 2024-08-15 09:16
> do you think this fix may also affect #2029 ?

Probably yes. Because the `FluentNavGroup` uses also the `FluentMenu`.

**Comment by vnbaaij** [comment] 2024-08-21 10:52
Closing this as the MenuProvider PR has been merged. Will be in next release. 

As mentioned, you can immediately test your code using the Preview package: https://github.com/microsoft/fluentui-blazor/blob/dev/docs/using-latest-daily.md

**Closed by vnbaaij** 2024-08-21 10:52 UTC
Labels: status:planned
