### ISSUE TITLE
rfc: Inconsistence of NavMenu Item Background

### ISSUE THREAD

**Issue by Kumima** [microsoft/fluentui-blazor#954] opened 2023-11-14 08:57 UTC
There is noticeable background for NavMenu Item, which is set as `--neutral-fill-stealth-rest`. But the default background of `body` is `--neutral-fill-layer-rest` which results in color difference. For demo document site, the background color is manually set as `--neutral-layer-1` to make nav and content have the same background. Isn't this weird?
![image](https://github.com/microsoft/fluentui-blazor/assets/93973732/e6c06a66-875a-4def-a0fb-eb9dd65a65ca)

**Comment by ggomarighetti** [comment] 2023-11-14 12:01
Hello!

Could you adapt the issue to the template/format available? Since there is information and details that you did not provide, such as the version of the library you are using or a way to replicate it.

In the attached screenshot, taken a few moments ago, of the 4.0 version of the library and available on fluentui-blazor.net, I can't see the bug in the design tokens.

Best regards!

![image](https://github.com/microsoft/fluentui-blazor/assets/59489394/40b73df0-2978-41e3-89aa-849028324605)

**Comment by vnbaaij** [comment] 2023-11-14 23:27
It is not a bug. It is a design choice I made which can be overruled by styling. Closing this as not actionable.

**Closed** 2023-11-15 06:45 UTC
