### ISSUE TITLE
MAUI Project can not import  web-components script automatically

### ISSUE THREAD

**Issue by RiuHDuo** [microsoft/fluentui-blazor#404] opened 2023-05-23 06:41 UTC
I created a MAUI-Blazor project with VS 2022.
and installed `Microsoft.Fast.Components.FluentUI 2.3.2`
![image](https://github.com/microsoft/fluentui-blazor/assets/830134/480c9497-be0c-4691-8995-c296588b3fda)

Add `@using Microsoft.Fast.Components.FluentUI` in _Imports.razor.
![image](https://github.com/microsoft/fluentui-blazor/assets/830134/132cb563-40a9-40a3-8669-fbe9f8112975)

Add <link> tag in `index.html`
![image](https://github.com/microsoft/fluentui-blazor/assets/830134/f0381615-d826-4535-80b0-0018feaf4e09)

Followed documents modified `Promgram.cs`
![image](https://github.com/microsoft/fluentui-blazor/assets/830134/4cf36925-2c90-4d83-9e84-a0a513fff79b)

Add sample code in index.razor
```
<FluentCard Style="padding: 1.5rem; width: 400px; height: 250px; ">
  <h2>Hello World!</h2>
  <FluentButton Appearance="@Appearance.Accent">Click Me</FluentButton>
</FluentCard>
```
App can not work well.
![image](https://github.com/microsoft/fluentui-blazor/assets/830134/2b2809b8-8863-4a28-99ad-769fe2ff3538)

If add web-component script in `index.html`.
![image](https://github.com/microsoft/fluentui-blazor/assets/830134/ce90af13-9e06-4a36-8658-e1b31b1acfd2)

it will work well.
![image](https://github.com/microsoft/fluentui-blazor/assets/830134/219f39db-2871-4f2c-9b27-168b443fa3f0)

**Comment by LuohuaRain** [comment] 2023-05-31 05:28
Confirmed

**Comment by andreisaperski** [comment] 2023-05-31 12:50
Looks like the root cause for this issue is the same as for [#327](https://github.com/microsoft/fluentui-blazor/issues/327).

Microsoft.Fast.Components.FluentUI package has an initializer [Microsoft.Fast.Components.FluentUI.lib.module.js](https://github.com/microsoft/fluentui-blazor/blob/354fdd5e6e6a151dc15950d830f5b082720ae77c/src/Microsoft.Fast.Components.FluentUI/wwwroot/Microsoft.Fast.Components.FluentUI.lib.module.js#L144) which loads web-components.js, but this initializer is ignored by Blazor Hybrid.

Build generates [AppName].modules.json file (bin\[Configuration]\[FW]\[Platform]\AppX\wwwroot\[AppName].modules.json) and populates it with found initilizers, but blazor.webview.js doesn't use this file. 
It loads initializers from ['_framework/blazor.modules.json'](https://github.com/dotnet/aspnetcore/blob/690d78279e940d267669f825aa6627b0d731f64c/src/Components/Web.JS/src/JSInitializers/JSInitializers.WebView.ts#LL7C17-L7C17) instead. [blazor.modules.json](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebView/WebView/src/blazor.modules.json) contains an empty array, it's embeded as resource in Microsoft.AspNetCore.Components.WebView and provided to blazor.webview.js by WebViewManager as is - array of initializers is always empty.

As sort of PoC, replaced '_framework/blazor.modules.json' with 'MauiApp1.modules.json', rebuilt Microsoft.AspNetCore.Components.WebView and copied new version into bin folder:

![image](https://github.com/microsoft/fluentui-blazor/assets/30940385/02c1c147-3be3-426d-a2f2-fa3d9e34a160)

Microsoft.Fast.Components.FluentUI.lib.module.js was loaded and controls initialized properly

**Comment by vnbaaij** [comment] 2023-05-31 17:37
@andreisaperski Can you test if custom web component events (like accordion change event) work with this setup as well?

**Comment by vnbaaij** [comment] 2023-05-31 20:42
So if people want to use the library in MAUI, we just need to tell them to compile their own WebView and everything works! 🤣🤣

**Comment by andreisaperski** [comment] 2023-05-31 21:17
There's another option )
![image](https://github.com/microsoft/fluentui-blazor/assets/30940385/aa632a7a-6e63-4aac-97b5-a48be89a6356)

**Comment by vnbaaij** [comment] 2023-06-02 10:18
@andreisaperski please chime in on the issue in the aspnetcore repo I linked to above

**Comment by andreisaperski** [comment] 2023-06-02 11:27
@vnbaaij not sure if i can add anything there, the comment you linked there, reflects all i have

**Comment by andreisaperski** [comment] 2023-06-08 22:11
There's a simpler workaround: intercept '_framework/blazor.modules.json' and provide proper JS initializers file (created by build). You can drop this [initializersLoader.windows.js](https://github.com/andreisaperski/fluentui-blazor/blob/hybrid-examples/examples/FluentUI.Demo.Hybrid.Shared/wwwroot/js/initializersLoader.windows.js) into wwwroot folder of app and add script tag for it to index.html right before '_framework/blazor.webview.js' tag:

```xml
<script app-name="FluentUI.Demo.Hybrid.MAUI" src="./_content/FluentUI.Demo.Hybrid.Shared/js/initializersLoader.windows.js"></script>
<script src="_framework/blazor.webview.js"></script>
```

'app-name' attribute needs to match app's assembly name - initializersLoader uses 'app-name' to resolve name of the file with initializers.
initializersLoader replaces 'fetch' function with another one which provides the right file instead of empty blazor.modules.json. 'fetch' is restored to its original state once '_framework/blazor.modules.json' request is intercepted.

When original issue is resolved, all that need to be done is to remove the tag and the script.

**Comment by vnbaaij** [comment] 2023-06-09 13:16
Adding these instructions to the Blazor Hybrid section in the readme!!

**Comment by vnbaaij** [comment] 2023-06-10 18:01
Closing this as we now have a workaround. See https://github.com/microsoft/fluentui-blazor#tempory-workaround-for-maui-issues for the details

**Closed by vnbaaij** 2023-06-10 18:01 UTC

**Comment by Kalyxt** [comment] 2024-09-11 11:02
> There's a simpler workaround: intercept '_framework/blazor.modules.json' and provide proper JS initializers file (created by build). You can drop this [initializersLoader.windows.js](https://github.com/andreisaperski/fluentui-blazor/blob/hybrid-examples/examples/FluentUI.Demo.Hybrid.Shared/wwwroot/js/initializersLoader.windows.js) into wwwroot folder of app and add script tag for it to index.html right before '_framework/blazor.webview.js' tag:
> 
> ```
> <script app-name="FluentUI.Demo.Hybrid.MAUI" src="./_content/FluentUI.Demo.Hybrid.Shared/js/initializersLoader.windows.js"></script>
> <script src="_framework/blazor.webview.js"></script>
> ```
> 
> 'app-name' attribute needs to match app's assembly name - initializersLoader uses 'app-name' to resolve name of the file with initializers. initializersLoader replaces 'fetch' function with another one which provides the right file instead of empty blazor.modules.json. 'fetch' is restored to its original state once '_framework/blazor.modules.json' request is intercepted.
> 
> When original issue is resolved, all that need to be done is to remove the tag and the script.

Doesn't work for me. I am running it on android emulator and all I get is `[chromium] [INFO:CONSOLE(1)] "Uncaught (in promise) SyntaxError: Unexpected token ?", source: https://0.0.0.0/_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js (1)` . App is then frozen at startup. I am using one of Geralds projects in MAUI blazor hybrid workshop.

![edgeinspector](https://github.com/user-attachments/assets/472a593b-46a6-4ed2-be91-20ece7aff79f)
![monkeyfinder](https://github.com/user-attachments/assets/66d91449-1107-4598-bb0e-bb1d10553c8b)

**Comment by vnbaaij** [comment] 2024-09-11 21:01
@Kalyxt is this on .NET 8 or 9?

**Comment by Kalyxt** [comment] 2024-09-12 08:01
@vnbaaij .NET 8 

`<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.9.3" />`
`<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.82" />`
`<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.82" />`
`<PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="8.0.82" />`
`<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />`
