### ISSUE TITLE
Error in demo FluentTabs page in Dynamic section "Could not find 'fluentOverflowResized'"

### ISSUE THREAD

**Issue by ZnowuJa** [microsoft/fluentui-blazor#2338] opened 2024-07-08 09:54 UTC
Hi,

In documentation [FluentTabs ](https://www.fluentui-blazor.net/Tabs)page in section with dynamic there is an error **when you try to delete one of tabs**.
Full error message:

> Could not find 'fluentOverflowResized' ('fluentOverflowResized' was undefined). Error: Could not find 'fluentOverflowResized' ('fluentOverflowResized' was undefined). at https://www.fluentui-blazor.net/_framework/blazor.webassembly.js:1:368 at Array.forEach (<anonymous>) at l.findFunction (https://www.fluentui-blazor.net/_framework/blazor.webassembly.js:1:336) at w (https://www.fluentui-blazor.net/_framework/blazor.webassembly.js:1:5079) at https://www.fluentui-blazor.net/_framework/blazor.webassembly.js:1:2872 at new Promise (<anonymous>) at b.beginInvokeJSFromDotNet (https://www.fluentui-blazor.net/_framework/blazor.webassembly.js:1:2835) at Object.vn [as invokeJSJson] (https://www.fluentui-blazor.net/_framework/blazor.webassembly.js:1:58849) at https://www.fluentui-blazor.net/_framework/dotnet.runtime.8.0.6.scyrrn9hx4.js:3:178364 at Tl (https://www.fluentui-blazor.net/_framework/dotnet.runtime.8.0.6.scyrrn9hx4.js:3:179198)

Regards

**Comment by michelmoorlag** [comment] 2024-07-08 13:08
I have the same issue when I upgrade my existing application from  4.8.1 to 4.9.0. So with 4.8.1  there is no issue and after upgrade to 4.9.0 this issue seems to appear.

**Comment by vnbaaij** [comment] 2024-07-08 14:02
Yes, confirmed this is a bug because of some internal renaming/refactoring. Will be fixed in 4.9.1

**Closed** 2024-07-08 21:47 UTC
Labels: bug, status:in-progress

**Comment by michelmoorlag** [comment] 2024-07-12 08:07
> Yes, confirmed this is a bug because of some internal renaming/refactoring. Will be fixed in 4.9.1

I can confirm that 4.9.1. fixed the issue for me.
@vnbaaij Thank you
