### ISSUE TITLE
FluentNavGroup 4.8.0 exception

### ISSUE THREAD

**Issue by Seanxwy** [microsoft/fluentui-blazor#2239] opened 2024-06-21 03:48 UTC
# 🐛 Bug Report

The first FluentNavGroup does not work properly, and the same is true in the demo website, it cannot be expanded or collapsed normally. When you roll back to 4.7.2, it can be expanded or collapsed normally.

## 💻 Repro or Code Sample

https://www.fluentui-blazor.net/WhatsNew

## 🤔 Expected Behavior

Need to be able to expand and collapse normally

## 😯 Current Behavior

The default folded items cannot be expanded, and the expanded items cannot be folded. Interaction abnormality

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment] 2024-06-21 05:37
Duplicate of #2211. You can confirm it is fixed with the preview package.

**Closed** 2024-06-21 05:37 UTC
Labels: closed:duplicate
