### ISSUE TITLE
fix: FluentUI Icons breaks VS intellisense in V3

### ISSUE THREAD

**Issue by AndyEdmonds** [microsoft/fluentui-blazor#679] opened 2023-09-02 04:53 UTC
If you've used icons in version 2, you will be attempting to upgrade them to V3.
The process of editing an existing .razor file in visual Studio 17.6.6  containing FluentIcons breaks as intellisense tries to cope with the editing of the FluentIcon. This results in VS hanging and requiring a restart.
This bug may be in FluentUI Blazor or VS. 
The only solution is to edit these files outside of VS, or to save changes before intellisense catches up..
This happens in two separate blazor projects. 
To reproduce:

In the most recent VS, open a solution containing a V2 project containing Icons.
Open the razor file containing icons in VS
Edit the "name" tag in the FluentIcon to convert to "Icon".
Edit the text part of the tag to the new format
Delete the old size and fill type tags.
At some point during this process intellisense will catch up and VS will hang,

So from: 
```
<FluentIcon Slot="start" Name="@FluentIcons.BrainCircuit" Size="@IconSize.Size24" Color=Color.Lightweight/>
```
to:
```
<FluentIcon Icon="@Icons.Regular.Size24.BrainCircuit" Slot="start" Color="Color.Lightweight" />
```

**Comment by vnbaaij** [comment] 2023-09-02 05:38
Duplicate of #643. Closing this one.

**Closed** 2023-09-02 05:38 UTC
