### ISSUE TITLE
fix: Dispatcher Exception in Debouncer 4.8.x+

### ISSUE THREAD

**Issue by Mike-E-angelo** [microsoft/fluentui-blazor#2466] opened 2024-07-28 18:45 UTC
# 🐛 Bug Report

Setting the `Immediate` property to `true` on the `FluentTextField` in any version after 4.7 results in a dispatcher exception as it appears the invoked delegate is not being invoked on the same dispatcher of the component.

## 💻 Repro or Code Sample

I am encountering this on the `FluentTextField` when it sets the `Immediate` property to `true` when the version of `Microsoft.FluentUI.AspNetCore.Components` is anything 4.8.x or above.  This problem does not happen on 4.7.2.

## 🤔 Expected Behavior

No errors, please. 😊  The debouncer should execute the delegate on the same thread as the component dispatcher.

## 😯 Current Behavior

In the case of `FluentTextField` with `Immediate=true`, I get the error here in 4.8.x+:

![image](https://github.com/user-attachments/assets/d1029daf-ac02-4efa-bf66-1eaac3693bdf)

## 💁 Possible Solution

I am currently reverting back to 4.7.x to avoid this issue.

## 🔦 Context

Everything else works well. 😊

## 🌍 Your Environment

* OS & Device: Windows 10 on PC
* Browser Chrome
* .NET and Fluent UI Blazor library Version 8.0 / 4.8+

**Comment by dvoituron** [comment] 2024-07-29 08:31
I cannot reproduce your issue.

I've added `Immediate` to the first sample of the demo site (server project), and all seems correct.
```
<p>Without label:</p>
<FluentTextField @bind-Value=value1 Immediate AriaLabel="No label"></FluentTextField>
<p>You entered: @value1</p>
```

Can you give us a sample code to reproduce this problem?

**Comment by Mike-E-angelo** [comment] 2024-07-29 09:26
Hi @dvoituron thank you for your investigation and patience.  `Immediate="true"` is one part, but I just now learned that you need to set the `ImmediateDelay` to introduce this issue as that is what incorporates the `Debouncer`:

```
@page "/"
@rendermode InteractiveServer

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

<EditForm Model="@Subject">
    <DataAnnotationsValidator />
    <Microsoft.FluentUI.AspNetCore.Components.FluentTextField @bind-Value="@Subject.Message" Immediate="true" ImmediateDelay="750" />
</EditForm>
@code
{
    [Parameter]
    public Model Subject { get; set; } = new();

    public sealed class Model
    {
        public string Message { get; set; } = "hello world";
    }
}

```

**Comment by Mike-E-angelo** [comment] 2024-07-29 15:46
FWIW I am using [these classes](https://github.com/DragonSpark/Framework/blob/d626a5d5bfdf3fda42fb6306ec3e6300631a07db/DragonSpark.Presentation/Components/Forms/FluentTextField.cs) as a workaround for now.

**Comment by cduluCNB** [comment] 2024-08-06 18:25
I also want to report that I'm also getting the same message with the same stack trace (please see attachments).

The SearchTextBoxChanged is an async method, that gets the data and populates a FluentDataGrid. This is the following pseudocode:

MyGrid?.SetLoadingState(true);
await InvokeAsync(StateHasChanged);

MyList = await GetListAsync();

MyGrid?.SetLoadingState(false);
await InvokeAsync(StateHasChanged);

Not sure if I need to be invoking StateHasChanged after setting the loading state on the grid, however.

![FluentSearch 20240806](https://github.com/user-attachments/assets/3cf06551-b621-4094-99ab-5500df7b7211)
![Call Stack 20240806](https://github.com/user-attachments/assets/67dc58fb-51d0-4733-8274-7fa6879bc101)
![Error 20240806](https://github.com/user-attachments/assets/931a07d9-583a-44ec-a5ac-749dc3912c3b)

**Comment by vnbaaij** [comment] 2024-08-20 18:50
Fixed this by changing `OnValidateStateChanged` in `FluentInputBase` to use `InvokeAsync(StateHasChanged);` instead of just `StateHasChanged()`. 

Will be in next release.

**Closed by vnbaaij** 2024-08-20 18:50 UTC
Labels: needs: repro code or repository

**Comment by cduluCNB** [comment] 2024-08-20 21:24
Hi @vnbaaij thank you so much!

Since you made the fix in FluentInputBase, do I still need to create a new issue for FluentSearch?

**Comment by vnbaaij** [comment] 2024-08-20 21:29
Probably not, no. Please try the preview package and see if it resolves your issue too. To use the preview NuGet Feed see 
https://github.com/microsoft/fluentui-blazor/blob/dev/docs/using-latest-daily.md

**Comment by cduluCNB** [comment] 2024-09-04 20:17
Hi @vnbaaij I'm still getting an error, I was able to narrow it down to the following line in FluentInputBase.cs:

I've committed a fix that I'll create a pull request for, but before I do that, I need to do some more investigation as to why my app is throwing this specific error.

![2024-09-04 13_11_33 - FluentInputBase cs](https://github.com/user-attachments/assets/7730f5d4-00b3-4324-8a2c-fd57ad68f896)

**Comment by cduluCNB** [comment] 2024-09-05 15:29
I did a bit more investigation and the issue happens with the following conditions:

- Immediate = true
- ImmediateDelay > 0
- There is a DataAnnotationsValidator added to the EditForm
- Either a FluentValidationSummary/ValidationSummary/FluentValidationMessage is also added to the EditForm.

Not sure how to describe this, but it seems like there's an issue (race condition?) with the EditContext being moved to a separate thread from the Dispatcher because of the Debouncer.

I'll be submitting the pull request - it's a small change, basically calling InvokeAsync to bring back the EditContext into the same thread as the dispatcher.

Here is some repro code:

```
@page "/"
@using System.ComponentModel.DataAnnotations

<EditForm EditContext="@_formContext">
    <DataAnnotationsValidator />
    <FluentValidationSummary/>
    @* <ValidationSummary /> *@
    <FluentTextField @bind-Value="@_search!.SearchText"
                     Immediate="true"
                     ImmediateDelay="500" />
    <FluentValidationMessage For="() => _search!.SearchText" />
</EditForm>

@code
{
    private SearchModel? _search;
    private EditContext? _formContext;

    protected override void OnInitialized()
    {
        base.OnInitialized();

        _search = new SearchModel() { SearchText = string.Empty };
        _formContext ??= new EditContext(_search);
    }

    public class SearchModel()
    {
        [StringLength(4, ErrorMessage = "Search term is too long.")]
        public string? SearchText { get; set; }
    }
}

```
