### ISSUE TITLE
fix: [The FluentDialogProvider component cannot function properly when deployed in Release mode on iis] in [FluentDialogProvider]

### ISSUE THREAD

**Issue by sswi** [microsoft/fluentui-blazor#1329] opened 2024-01-15 14:42 UTC
# 🐛 Bug Report
The FluentDialogProvider component cannot function properly when deployed in Release mode on IIS

## 💻 Repro or Code Sample
```xml
<FluentStack>
    <FluentButton OnClick="ShowDialogAsync" Title="Dialog">Success</FluentButton>
    <FluentButton OnClick="ShowMessageBoxAsync" Title="MessageBox">Welcome</FluentButton>
</FluentStack>

<FluentToastProvider />
<FluentDialogProvider />
<FluentTooltipProvider />
<FluentMessageBarProvider />
```

```csharp
    [Inject]
    private IDialogService DialogService { get; set; } =default!;

    private async Task ShowDialogAsync()
    {
        var dialogResult = await DialogService.ShowSuccessAsync("Welcome to Dongbei");
    }

    private async Task ShowMessageBoxAsync()
    {
        var messageBoxResult = await DialogService.ShowMessageBoxAsync(new DialogParameters<MessageBoxContent>()
            {                
                Content = new()
                {
                    Title = "Welcome",
                    Message="Welcome to Dongbei",  
                    MarkupMessage = new MarkupString("❤️"),
                    Icon = new Icons.Regular.Size24.Heart(),
                    IconColor = Color.Error,
                },
                PrimaryAction = "OK",                
                Width = "300px",
            });
    }
```

## 🤔 Expected Behavior
The dialog box prompt message should be visible

## 😯 Current Behavior
Debugging mode runs normally

https://github.com/microsoft/fluentui-blazor/assets/39110708/7306a8dc-99ac-447d-99a7-7593fa0450e6

Release mode does not work properly

https://github.com/microsoft/fluentui-blazor/assets/39110708/f07a726b-3f92-4eea-8b68-3936a3079150

## 🌍 Your Environment

.net8.0 blazor web app, auto model,global 
Microsoft Fluent UI Blazor components 4.3.1

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment] 2024-01-15 23:23
Duplicate of #1255

**Closed by vnbaaij** 2024-01-15 23:23 UTC
Labels: closed:duplicate
