### ISSUE TITLE
FluentInputLabel With css set, the default fluent-input-label style is lost

### ISSUE THREAD

**Issue by Seanxwy** [microsoft/fluentui-blazor#1946] opened 2024-04-26 08:49 UTC
```
<FluentEditForm Model="@UserQuery">
    <FluentStack Orientation="Orientation.Horizontal" VerticalAlignment="VerticalAlignment.Center" Wrap="true">
        <div style="display:flex" class="me-2">
            <FluentInputLabel Label="Username" class="me-2"></FluentInputLabel>
            <FluentTextField Name="identifier" @bind-Value="UserQuery.UserName" />
        </div>
        <div style="display:flex" class="me-2">
            <FluentInputLabel Label="Email"></FluentInputLabel>
            <FluentTextField Name="identifier" @bind-Value="UserQuery.UserName" />
        </div>
        <div>
            <FluentButton>Search</FluentButton>
        </div>
    </FluentStack>
</FluentEditForm>
```

![image](https://github.com/microsoft/fluentui-blazor/assets/15828095/2fe89277-1d71-47ae-b41f-53e29036cadc)

![image](https://github.com/microsoft/fluentui-blazor/assets/15828095/2256c8b8-a189-4ee6-a377-22f74c986a71)

**Comment by vnbaaij** [comment] 2024-04-26 14:28
Ok, **you really need to start using the issue template**. I have no idea what I'm looking at . What is the expected behavior? What are you seeing? How could it be solved?

I've asked before and will just start closing your issues if you won't do it.

**Comment by Seanxwy** [comment] 2024-04-26 15:07
Okay, start using question templates from now on.
FluentInputLabel will have class= fluent-Input-label by default. When I set the FluentInputLabel class. The default fluent-input-lable style widget has been replaced with a custom class value

**Comment by vnbaaij** [comment] 2024-04-28 08:19
The `FluentInputLabel` component only uses the 'fluent-iput-label' class by default. It does not expose a `class` parameter. It does expose the AdditionalAtrributes so your class will overwirte the defualt class. That is by design.
From the source code:

```
 <label for="@ForId" class="fluent-input-label" @attributes="@AdditionalAttributes"
```

I f you do not want this, you shoud just use label

**Closed by vnbaaij** 2024-04-28 08:19 UTC
Labels: needs: author feedback
