### ISSUE TITLE
FluentButton triggers form submit on enter key

### ISSUE THREAD

**Issue by MisterGoodcat** [microsoft/fluentui-blazor#1200] opened 2023-12-24 14:36 UTC
# 🐛 Bug Report

When focused, `FluentButton` triggers a form submit on enter. A standard button does not do this.

## 💻 Repro or Code Sample

`<FluentButton Type="ButtonType.Button" @onclick="() => {}">Click</FluentButton>`

Focus the button, hit enter, the containing form is submit.

`<button type="button" @onclick="() => {}">Click</button>` 

Focus the normal button, hit enter, the containing form is not submit.

## 🤔 Expected Behavior

The `FluentButton` should behave like a standard button?

**Comment by vnbaaij** [comment] 2023-12-24 15:47
This is a duplicate of #1050 (although different in wording. It is in issue in the underlying code. See also 
 https://github.com/microsoft/fluentui-blazor/issues/1050#issuecomment-1846929719

**Closed by vnbaaij** 2023-12-24 15:47 UTC
