### ISSUE TITLE
fix: Clear button is no longer functioning in AutoComplete

### ISSUE THREAD

**Issue by lasbrojen** [microsoft/fluentui-blazor#2903] opened 2024-11-04 20:51 UTC
Hi ❤️

It seems that the Clear button in AutoComple is no longer functioning. I've noticed the same issue on the demo site as well. I've included a GIF below for reference.

Thank you for this nugget ✌️

🐛 Bug Report

![Image](https://github.com/user-attachments/assets/43f38444-c29c-4d27-b837-5389298d60df)

**Comment by NabaviFard-Mahdi** [comment] 2024-11-04 21:24
It issues this error
```
 focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
Element with focus: svg
Ancestor with aria-hidden:  <svg slot=​"end" style=​"width:​ 12px;​ fill:​ var(--accent-fill-rest)​;​ cursor:​ pointer;​" focusable=​"false" viewBox=​"0 0 16 16" aria-hidden=​"true" tabindex=​"0" role=​"button">​slot<title>​Clear​</title>​<!--!--><path d=​"m2.59 2.72.06-.07a.5.5 0 0 1 .63-.06l.07.06L8 7.29l4.65-4.64a.5.5 0 0 1 .7.7L8.71 8l4.64 4.65c.18.17.2.44.06.63l-.06.07a.5.5 0 0 1-.63.06l-.07-.06L8 8.71l-4.65 4.64a.5.5 0 0 1-.7-.7L7.29 8 2.65 3.35a.5.5 0 0 1-.06-.63l.06-.07-.06.07Z">​</path>​</svg>​
``` 

![Image](https://github.com/user-attachments/assets/7bdcd442-76a1-4b47-bc03-39d20a83b576)

**Comment by dvoituron** [comment] 2024-11-05 12:23
The problem is not related to this error (which will be fixed quickly). I'm working on it.

**Comment by dvoituron** [comment] 2024-11-05 13:24
Will be fixed in the next Release

**Closed by dvoituron** 2024-11-05 13:24 UTC
Labels: status:in-progress
