### ISSUE TITLE
FluentUI-Blazor templet v 4.9.3 for VS 2022

### ISSUE THREAD

**Issue by HeniekStawski** [microsoft/fluentui-blazor#2483] opened 2024-08-03 08:11 UTC
Windows 11 Pro,
Browser MS Edge
Fluent UI Blazor library Version 4.9.3
When I build and run the generic Web app from Fluent UI Blazor template, it gives me runtime error when refreshing Counter page.

**Comment by dvoituron** [comment] 2024-08-03 08:18
Without having more information on the code you're using (what configurations are defined in the template), we can't give you any more information.

Perhaps your problem is related to this one, detected recently? #2476
If not, can you give us a Git Repo with your code?

**Comment by HeniekStawski** [comment] 2024-08-04 00:54
This is repository of Fluentui Blazor template.
https://github.com/HeniekStawski/FluentBlazorApp17

**Comment by coderdnewbie** [comment] 2024-08-04 18:40
I tried it out, and if you add `builder.Services.AddFluentUIComponents();` into the Program.cs of FluentBlazorApp17.Client, the error should no longer happen. This is the full code for the Program.cs file

```
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.FluentUI.AspNetCore.Components;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.Services.AddFluentUIComponents();

await builder.Build().RunAsync();
```

Please try it and see if it works for you. Of course this does indicate an issue with the template.

**Comment by dvoituron** [comment] 2024-08-05 07:25
Thanks @coderdnewbie.

It's the exact same issue detected in #2476
I think the problem is now solved (an update will be included in the next release).

**Closed by dvoituron** 2024-08-05 07:25 UTC
Labels: needs: repro code or repository

**Comment by HeniekStawski** [comment] 2024-08-05 12:41
Thank you,
It solves the problem.
Heniek
