### ISSUE TITLE
Fluent Paginator with remote data

### ISSUE THREAD

**Issue by satyajit-behera** [microsoft/fluentui-blazor#2169] opened 2024-06-08 07:18 UTC
The fluent paginator seems to do paging with IQueryable data. 

Can we have the behavior to including paging with remote data while using Items="@FilteredItems" also and not only using ItemsProvider="foodRecallProvider".

This will help us pass the page number and records for querying a REST data from remote server and use default paging at the same time.

Thanks

**Comment by vnbaaij** [comment] 2024-06-08 08:40
Yes, it does that by design (comes from QuickGrid).

We currently have no plans (nor capacity) to change that. But we do take PR's, so if you or someone else wants to work on this, that would be great.

**Comment by satyajit-behera** [comment] 2024-06-08 08:47
Thanks.

In the mean time, following may help:
```
<div style="height: 434px; overflow:auto;" tabindex="-1">
    <FluentDataGrid Loading="true" ItemsProvider="foodRecallProvider" Virtualize="true" ItemSize="46" GenerateHeader="GenerateHeaderOption.Sticky" TGridItem="FoodRecall" >
        <PropertyColumn Title="ID" Property="@(c => c!.Event_Id)" />
        <PropertyColumn Property="@(c => c!.State)" Style="color: #af5f00 ;" />
        <PropertyColumn Property="@(c => c!.City)" />
        <PropertyColumn Title="Company" Property="@(c => c!.Recalling_Firm)" Tooltip="true"/>
        <PropertyColumn Property="@(c => c!.Status)" />
        <TemplateColumn Title="Actions" Align="@Align.End">
            <FluentButton aria-label="Edit item" IconEnd="@(new Icons.Regular.Size16.Edit())" OnClick="@(() => DemoLogger.WriteLine("Edit clicked"))" />
            <FluentButton aria-label="Delete item" IconEnd="@(new Icons.Regular.Size16.Delete())" OnClick="@(() => DemoLogger.WriteLine("Delete clicked"))" />
        </TemplateColumn>
    </FluentDataGrid>
</div>
```

Is it possible to access the corresponding value ("ID") for a row cell in the click event while using **ItemsProvider** instead of **Items**? This is using Remote data and foodRecallProvider

**Comment by vnbaaij** [comment] 2024-07-23 19:47
Closing this as no progress made.

**Closed by vnbaaij** 2024-07-23 19:47 UTC
Labels: community:request, community:contribution
