### ISSUE TITLE
 add [Virtualize] to/in [Datagrid] using remote data and pagination

### ISSUE THREAD

**Issue by sardar97** [microsoft/fluentui-blazor#1944] opened 2024-04-26 00:55 UTC
when i use remote data to load my data and using pagination the Virtualize is not working!
like i showed in the video.
and here is example of my codes  : 
`<FluentDataGrid ItemsProvider="@_customerProvider" ResizableColumns="false" 
                         Virtualize="true"  Style="width: 100%" Loading="true" Pagination="@_pagination">`

and please tell me if there is a way to use **Skeleton** inside datagrid?!
Example Video :
https://github.com/microsoft/fluentui-blazor/assets/96167344/b0b4bbe6-307e-45b1-a50b-55baa312889d

**Comment by vnbaaij** [comment] 2024-04-26 05:16
Please supply us with reproduction code in the form of a project or repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will get closed automatically in **3** days

Help us to help you. Thanks

**Comment by sardar97** [comment] 2024-04-26 12:33
`@page "/customer"
@rendermode @(new InteractiveAutoRenderMode(prerender:false))
@using System.Diagnostics 
@inject HttpClient _Http
@inject NavigationManager _NavigationManager


<FluentStack Orientation="Orientation.Vertical" VerticalAlignment="VerticalAlignment.Center"
            HorizontalAlignment="HorizontalAlignment.Center" >
 
    <h1>@_ErorMsg</h1>

    <FluentCard Width="100%" >
        <h3>Customer</h3>
        <FluentDataGrid ItemsProvider="@_customerProvider" ResizableColumns="false" 
                         Style="width: 100%" Loading="true" Pagination="@_pagination">
            <PropertyColumn Property="@(p=>p.name)" Sortable="true"
                            Filtered="!string.IsNullOrWhiteSpace(nameFilter)" Tooltip="true" Title="Name">
                <ColumnOptions >
                    <div class="search-box">
                        <FluentSearch type="search" Autofocus=true @bind-Value="nameFilter"
                                      @oninput="HandleCountryFilter" @bind-Value:after="HandleClear" Placeholder="Name"/>
                    </div>
                </ColumnOptions>
            </PropertyColumn>
            <PropertyColumn Property="@(c => c.phone)" Sortable="true" Class="multiline-text"/>
            <PropertyColumn Property="@(c => c.address)" Sortable="true" Class="multiline-text"/>

        </FluentDataGrid>

        <FluentPaginator  State="@_pagination"   >
            <SummaryTemplate >
                Total rows :  <strong>@((_pagination.TotalItemCount ?? 0).ToString("N0"))</strong>
                <p>Time to load : @_loadingTime</p>
            </SummaryTemplate>

            <PaginationTextTemplate>
                <strong>@((_pagination.CurrentPageIndex + 1).ToString("N0"))</strong> of <strong>@((_pagination.LastPageIndex + 1).Value.ToString("N0"))</strong>
            </PaginationTextTemplate>
        </FluentPaginator>

    </FluentCard>

</FluentStack>`

`@code {

    
    PaginationState _pagination = new PaginationState { ItemsPerPage = 10 };
    string? nameFilter = null; 
    private string _loadingTime { get; set; }
    private string _ErorMsg { get; set; } 
 
    GridItemsProvider<Shared.Models.Customer>? _customerProvider;
 
     

     protected override async Task OnInitializedAsync()
    {         
       await LoadData(); 
    }

    private async Task LoadData()
    {
        _customerProvider = async req =>
        {
            
            Stopwatch _stopwatch =Stopwatch.StartNew();
            // Construct the URL with query parameters
            bool? sortingByAscending = req.SortByAscending!;
            string? column = string.Empty;
            if (req.SortByColumn is not null)
            {
                column = req.SortByColumn!.Title;
            }
            string apiUrl = $"{_NavigationManager.BaseUri}api/Customer";
            string queryParameters = 
                $"?skip={req.StartIndex}&take={req.Count}&sortingByAscending={sortingByAscending}&column={column.ToLower()}";
            Console.WriteLine("sardar url : "+queryParameters);
            if (!string.IsNullOrEmpty(nameFilter))
            {
                queryParameters += $"&where={Uri.EscapeDataString(nameFilter)}";
            }
            string fullUrl = apiUrl + queryParameters; 
            var response = await  _Http.GetFromJsonAsync<PaginationDTO.MyPaginationDTO>( fullUrl);
            _stopwatch.Stop();
            TimeSpan loadingTime2 = _stopwatch.Elapsed;
            _loadingTime = string.Format("{0:D2}h:{1:D2}m:{2:D2}s:{3:D3}ms",
                loadingTime2.Hours, loadingTime2.Minutes, loadingTime2.Seconds, loadingTime2.Milliseconds);
            // Check if response is successful and contains data 
            if (response != null && response.customers != null)
            {
                if (response.customers.Count <= 0)
                {
                    return GridItemsProviderResult.From(Array.Empty<Shared.Models.Customer>(), 0);
                }
                else
                {
                    return GridItemsProviderResult.From(items: response.customers, totalItemCount: response.totalCount);
                }
            }
            else
            { 
                return GridItemsProviderResult.From(Array.Empty<Shared.Models.Customer>(), 0);
            }
         
        };
        
    }
    
    private async Task HandleCountryFilter(ChangeEventArgs args)
    {
        if (args.Value is string value)
        {
            nameFilter = value;
        }

       await LoadData();
    }
    
    private async Task HandleClear()
    {
        if (string.IsNullOrWhiteSpace(nameFilter))
        {
            nameFilter = string.Empty;
            await LoadData();
        } 
    }
}`

**Comment by vnbaaij** [comment] 2024-04-26 13:01
Hi Sadar,

Can't run this code. Don't have `Shared.Models.Customer` and this is also not working:

```
 var response = await  _Http.GetFromJsonAsync<PaginationDTO.MyPaginationDTO>( fullUrl);
```

But looking at your original issue, I think it is not a really good way of working to use these together. Think you can better do an 'on-demand' loading per page requested. See the DataGrid Custom Paging example on how you can create your own buttons and hook into the handlers.

**Comment by sardar97** [comment] 2024-04-26 16:29
no if you look at my code for every new page I request a new http request for the API and it works fine but when I have 1M Record and sorting it take 700ms for each page. So for better user experience I want virtualize it or showing  a nice loading at top of the DataGrid. if you look at this MudBlazor example you will understand what I mean.
[https://try.mudblazor.com/snippet/vVhbT-s4EH7vn8CK9iFdcVyklfbhNI2AAgdWUBCt9jysVsgkLvXixJXtAAX1v-9M4tx6Q6yq7UOa2jPzfR6PZ8Z9eLhhIqWavSt9cJwZkT6R8cJYntARt_TS2jn9w6i04-ZusvhUojA9f2PJXHJDz5hl9EbFXJrOsUj_4ZElqDeUgqeWzKrXTicA9Ql7lJyMuX7hGlUH3rGf8ldykaVRkE-OLbP8kEyYeS4GUCw4lzwBI2EY-oXyPZeKxd2u1yHV54ynhg88qzPukUsFUuWPY82n8I7mvDDXCCZKyVOmhyq1aLgyk7Pkb5ZMFnM18PBJZ7974R3XQsUiIo6KCXpOsq07nrOIa9Jbt3ghuIzJZOAZq8GbHvmTyYwPZyx94jE6wgzC23TMmY5mvoGlkTsJtmZKxriSYsIjJ7HSKTIYeNUrBa9p2_RF81OJXUUqBSD8MvQG_KwFk_RCSMljWtrH2bF4B0fik97wWGSJR4aSGTPwEvvtyAurtedrch7tbXJpcMkZ0N_s5llYxcRYaXvNHrkk1dvAS_XDFAE89JrzuxeOdAHfUnOUZl9EMOIp3YQxhvH9oaQs4RtXAuP7Q5krI6xQG9dz5-b2h5ZAOGxCulGSaYKzn2IFvQ3BEdyr1wmH5ALhuUIpJpgLHP5Ie-FxhJpvlo6y5JG7sIh3aeG-NvTqbd6phfvURKu2badW6fOGZnsbdmrXfmzo54Mt5aC35q9gpO55pHRstia3cKTAtI1mmNV1IUymKkvjlawW9DYbC64h-4LydgQnQCldM7lJN7hjT9vSBIZQPl1m1aDXlq4jLex0wFkxJx-54FyLF_ALuTpPs4RrlKhKCZmDjRg93m_JlqZqwbxu9DstKQHFzSrL5BVUS9O2UOR3YvKEOi5-DEiaSemM9Ho9EpgsSZhehNXIJdecvIK6SDLcTfLErUVdO-MF2UMyFRKyNo8JS2MCu5K_x7AGMtUqySVNXh9rnF4LqOTIzCKNtlZZ0iyyfl2XYWnw7OaWPqpN2ujdnNSAsFcmmm0A_cHtBVDFtuIEOQTXwtga2fde-SObi97c1duiaHf7FVphEZnTMy7Zwv_t6Kgx7XDxi_6cgX98Xtgmgzqsau74EVPiF3tGr8wItulW_5wJy_NS7je3sdtdK7Ga20ynBPuM_ppVB53nGYrhCu2WaVk8JMX3UCVzpgV4hd5qOB0QWE-p0nzIDP-vqJin_j_UX7yPCjhPx0tSDZR5rzGUp7Klt5nfV7DdxJRJ05hZdulEnWgN8dEIjvrEliEyhKRnmyLmVUBexICASKdV5epuiZ0IPEXqRuX7Gu9mPN7igT1dnAlIueiOBkg1dkgURCpRzond_prFR83Zc38Di0Yzs0ceGLtfYdFodvbpDbD6FRYrzdAemZSx_BU2jWZpj0zyI_Q5jWWneq1KXok3fhZzh4EllfxK6h_Y_sMpYs_cXxtcP1ruGOJlbr2g-F3yMWmevfogHpJyrCK3LKwu2xX3RYmY1PejoqxiV7RajlbqLoo0MgByo0Vhq6-h5UKWneWB40wjc9C6EQ8VXJPyDTBQxFIoT1G_05LAHie_L8NdCm9W4p2hOBR9PBMGq8lnV2jXtmSPEm6aEV65yvvmyiKdiHPDD62yOfnAjqEP64fHclUSG5YydHdLOpt44j43WWSpFblK8C_0xp1WUMztAg36nkmYlF737y2omG12o8Yqw_8Qiv54p-RV3loI7EbOces0bN02pk4F_zTQIq56uIkq4sjflv9d2EPxQ-ZL8o184DqXXvP8udD6Fw](url)

**Comment by vnbaaij** [comment] 2024-04-26 17:02
That MudBlazor example has nothing to do with Virtualize. It determines which records to show on a page by doing:

```
pagedData = data.Skip(state.Page * state.PageSize).Take(state.PageSize).ToArray();
```

So returning just the exact rows that should be shown on a page. I don't think this is a component issue but more a general paging/sorting of a large data set problem.

**Comment by vnbaaij** [comment] 2024-04-30 14:25
Closing due to no repro code provided

**Closed by vnbaaij** 2024-04-30 14:25 UTC
Labels: needs: repro code or repository
