### ISSUE TITLE
fix: rows attribute in all textArea controls

### ISSUE THREAD

**Issue by coleman-rik** [microsoft/fluentui-blazor#72] opened 2021-08-07 01:13 UTC
# 🐛 Bug Report

None of the text-area controls; fast-text-area, fluent-text-area, FluentTextArea honor the rows attribute.

## 💻 Repro or Code Sample

Use your own code or try the online version here: [https://explore.fast.design/components/fast-text-area](https://explore.fast.design/components/fast-text-area).  Change the value of the row attribute to anything you like.  

## 🤔 Expected Behavior

The size of the TextArea changes in response to the value of the rows attribute.

## 😯 Current Behavior

Absolutely nothing.

## 🔦 Context

Trying to set up a text area to hold the response containing a large amount of text from a rest call.  Unless, until this gets fixed I'll have to try CSS styles (hopefully it will work).

## 🌍 Your Environment
Windows 10 Pro x64
All Browsers; Firefox, Chrome, Vivaldi, Brave, Edge.
.Net 5, Microsoft.Fast.Components.FluentUI 0.3.0
JetBrains Rider 2021.2
Microsoft Visual Studio 2019 Pro.
Blazor Server

**Comment by Ogglas** [comment] 2023-06-01 10:26
Can this be fixed not @vnbaaij given the closed PR? https://github.com/microsoft/fast/issues/3869 https://github.com/microsoft/fast/pull/5856

**Comment by Ogglas** [comment] 2023-06-05 09:30
@vnbaaij Given that this issue has been open a long time: Could we add the possibility to override html textarea CSS and therefore enable the fix mentioned below with `height:auto`?

https://github.com/microsoft/fluentui/issues/27842

**Comment by vnbaaij** [comment] 2023-06-05 09:37
I actually committed a PR to the Fluent Web Components (https://github.com/microsoft/fluentui/pull/28135) to fix it there by implementing the same fix as in https://github.com/microsoft/fast/pull/5856. Hope to get that merged in in web-component script soon (it is already approved).

**Comment by Ogglas** [comment] 2023-06-05 09:50
Nice! I hope it can be released soon then :)

**Comment by c0g1t8** [comment] 2023-06-22 16:38
A workaround was asked for in #417, a duplicate of this issue. See the following: https://github.com/microsoft/fluentui-blazor/issues/417#issuecomment-1602965916

**Comment by vnbaaij** [comment] 2023-07-20 15:20
This has (finally!) been fixed with Fluent UI Web Components release 2.5.16. The new `web-components.min.js` file will be included in the next minor version (2.4.2) which we will release tomorrow.

**Comment by Ogglas** [comment] 2023-07-20 16:39
Good job @vnbaaij! 💯

**Comment by Ogglas** [comment] 2023-07-23 21:29
@vnbaaij Tested this now and there still seems to be some error. You can see that it does not work in the examples either:

https://www.fluentui-blazor.net/TextArea#rows-and-cols

Unfortunately I think this has to be reopened. 

It does work in 3.0.0-RC.1:

https://calm-sea-053fa6a03-365.westeurope.3.azurestaticapps.net/TextArea#rowsandcols

**Comment by vnbaaij** [comment] 2023-07-24 04:32
We are having an issue with the library not picking up the latest version of the script. Need to investigate what is happening. No 2.4.2 package because of that. Might take a while because of summer vacation.

**Closed** 2023-08-18 14:40 UTC
Labels: bug, area:fast, community:request, status:blocked
