### ISSUE TITLE
DateOnly, TimeOnly supports for Calendar/DatePicker/TimePicker

### ISSUE THREAD

**Issue by yongkeecho** [microsoft/fluentui-blazor#846] opened 2023-10-12 17:02 UTC
# 🙋 Feature Request

DateOnly supports for Calendar/DatePicker
TimeOnly supports for TimePicker

## 🤔 Expected Behavior

@bind-Variable or else variable takes DateOnly? or TimeOnly? 

## 😯 Current Behavior

@bind-Variable binds only with DateTime

## 💁 Possible Solution

Since @bind-Variable is already taken, introduce another variable of DateOnly? or TimeOnly?

## 🔦 Context

DatePicker is for picking a date, it is reasonable to support DateOnly data type.
TimePicker is for picking a time, it is reasonable to support TimeOnly data type.

**Comment by dvoituron** [comment] 2023-10-12 19:46
Hi,
At the moment, these components are created like this, by design.
Another reason is that we could create a "combined" component including date and time.

This could be an evolution in a future release, but it would mean we'd have two "Value" properties.
And I don't think that's very easy to use.

In the meantime, you can create a `SelectedValue` property that converts your `DateOnly`:

```csharp
private DateOnly? MyDate = DateOnly.FromDateTime(DateTime.Today.AddDays(-2));    // Sample initial value

private DateTime? SelectedValue
{
    get => MyDate?.ToDateTime(TimeOnly.MinValue);
    set => MyDate = (value is null ? null : DateOnly.FromDateTime(value ?? DateTime.MinValue));
}
```

And for the `TimeOnly`:

```csharp
private TimeOnly? MyTime = null;    // Sample initial value

private DateTime? SelectedValue
{
    get => MyTime is null ? null : DateTime.Now.Date.Add(MyTime?.ToTimeSpan() ?? TimeSpan.Zero);
    set => MyTime = (value is null ? null : TimeOnly.FromDateTime(value ?? DateTime.MinValue));
}
```

**Comment by vnbaaij** [comment] 2023-10-13 09:48
Closing this as not planned and workaround available

**Closed by vnbaaij** 2023-10-13 09:48 UTC

**Comment by vukasinpetrovic** [comment] 2024-01-05 16:41
@vnbaaij I just stumbled upon this also and I would say that it makes a lot of sense to incorporate that functionality into components, especially now that a lot of developers are using DateOnly and TimeOnly fields and this workaround looks really ugly if we have to use multiple fields in our component. Do you think that this would make it into planning or another workaround is possible?
My example is that I would use separate fields for time period, start date + start time and end date + end time, so I would have to have 4 custom private properties with manual mapping to my model, which seems a bit too excess code for such a simple binding.
What do you think?

**Comment by vukasinpetrovic** [comment] 2024-01-05 16:56
Also, why is it required that the bind-Value must be nullable DateTime? If I define in my model that it cannot be nullable (usually default is set to today) and I try to bind to my model, then I get the error saying: 

> "Argument 2: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback<System.DateTime>' to 'Microsoft.AspNetCore.Components.EventCallback'"

Is there a reason I'm forced to use nullable DateTime?

**Comment by vnbaaij** [comment] 2024-01-05 17:00
Otherwise you can't clear the field

**Comment by vnbaaij** [comment] 2024-01-05 17:02
I'll take a look to see if we can make it generic so you could use both nullable and non-nullable

**Comment by vukasinpetrovic** [comment] 2024-01-05 17:05
Hmm, that's a valid point, but many are used to having an option of preventing user clearing the field (they don't have X/clear button), in which case if they try to remove value or enter invalid one, it's reverted.

Example is that user is filtering results of a search, where the main parameter is date (today or tomorrow), so it makes no sense to be able to clear that field, but just set the required value.

I'm maybe too picky, but I'm just sharing what I'm used to while building apps.

Thank you, having option of both nullable and non-nullable would be amazing!

**Comment by dvoituron** [comment] 2024-01-11 13:35
Until we find a more sustainable solution, to simplify the use of `DateTime`, `DateOnly` and `TimeOnly`, we could add the extension methods `ToDateTime`, `ToDateOnly` and `ToTimeOnly` (in the lib). The usage will be:

1. If your variable is of type `Nullable<DateTime>`, you can continue to use `@bind-Value`.
2. For other types, you must use the syntax `value="..." ValueChanged="..."`

I find this an interesting alternative, until we find a better solution using the _generic_.
And, it doesn't cause any breaking changes in existing (and future) code.

```razor
<!-- Default usage -->
<FluentDatePicker @bind-Value="@MyDate0" />

<!-- Using conversion methods -->
<FluentDatePicker Value="@MyDate1" ValueChanged="@(e => MyDate1 = e.ToDateTime())" />
<FluentDatePicker Value="@MyDate2.ToDateTime()" ValueChanged="@(e => MyDate2 = e.ToDateOnly())" />
<FluentDatePicker Value="@MyDate3.ToDateTime()" ValueChanged="@(e => MyDate3 = e.ToDateOnly())" />

<ul>
    <li>@(MyDate0?.ToString("yyyy-MM-dd"))</li>
    <li>@(MyDate1.ToString("yyyy-MM-dd"))</li>
    <li>@(MyDate2?.ToString("yyyy-MM-dd"))</li>
    <li>@(MyDate3.ToString("yyyy-MM-dd"))</li>
</ul>

@code
{
    private DateTime? MyDate0 = DateTime.Today;
    private DateTime MyDate1 = DateTime.Today;
    private DateOnly? MyDate2 = DateOnly.FromDateTime(DateTime.Today);
    private DateOnly MyDate3 = DateOnly.FromDateTime(DateTime.Today);
}
```

Part of extension methods:
```csharp
public static DateTime ToDateTime(this DateOnly value) => value.ToDateTime(TimeOnly.MinValue);
public static DateTime ToDateTime(this DateOnly? value) => value == null ? DateTime.MinValue : value.Value.ToDateTime(TimeOnly.MinValue);
public static DateTime ToDateTime(this DateTime? value) => value == null ? DateTime.MinValue : value.Value;
public static DateOnly ToDateOnly(this DateTime? value) => value == null ? DateOnly.MinValue : DateOnly.FromDateTime(value.Value);
```

**Comment by vukasinpetrovic** [comment] 2024-01-11 13:42
@dvoituron This looks good to me, thank you 👍

**Comment by dvoituron** [comment] 2024-02-11 16:23
After a few "long" weeks, this PR could be useful: #1500
