### ISSUE TITLE
fix: potential component lifecycle issue with check boxes setting state

### ISSUE THREAD

**Issue by ApacheTech** [microsoft/fluentui-blazor#2668] opened 2024-09-17 09:09 UTC
# 🐛 Bug Report

Following the flow of code through the `FluentCheckBox` component, it's possible that we try to call `setFluentCheckBoxIndeterminate` before the page has been rendered, meaning that `JSRuntime` cannot make JavaScript interop calls. I'm aware that this may be a misunderstanding on my part, on the way that components are initialised.

## 💻 Repro or Code Sample

Here, we set the initial `value` to true: [https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Checkbox/FluentCheckbox.razor](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Checkbox/FluentCheckbox.razor), and set a handler for `oncheckedchange`.

We then set the value when we use the component:

```csharp

<FluentCheckBox @bind-Value="_checkState" />

@code
{
    private bool _checkState;
}
```

This would immediately cause `OnCheckedChangeHandlerAsync` to fire, within the pre-render stage, which even in a two state checkbox, calls `SetIntermediateAsync`, before `JSRuntime` is usable.

## 🤔 Expected Behaviour

`JSRuntime` wouldn't be called until later in the component lifecycle, at `OnAfterRenderAsync`.

## 😯 Current Behaviour

See above.

## 🔦 Context

I uncovered this while bug-hunting, with a different issue. I thought it worthy of note.

## 🌍 Your Environment

* OS & Device: Windows 11 Enterprise on PC
* Browser: FireFox 130.0
* .NET and Fluent UI Blazor library Version: `net8.0` and FluentUI 4.10.0

**Comment by ApacheTech** [comment] 2024-09-18 08:58
**Update:** The underlying issue that caused this problem was #2356, within a branch that FluentUI had not yet been updated to 4.10.0. The page has now been re-designed without any `FluentStack`. The infinite loop eventually caused the `JSException` for this bug to be thrown, and was caught in Application Insights.

**Comment by vnbaaij** [comment] 2024-09-18 09:36
So this can be closed?

**Comment by ApacheTech** [comment] 2024-09-18 09:40
No. Nothing about the flow of code within `FluentCheckbox` has changed because of #2356, so this issue still exists.

**Comment by ApacheTech** [comment] 2024-09-18 10:00
So far as I can see, the code flow I listed above is still accurate.

1. The checkbox sets its state to `true`.
2. When we find to a falsey bool, the `OnCheckedChangeHandlerAsync` fires.
3. Which will call `SetIntermediateAsync`.
4. Which will invoke the `JSRuntime`.

All of this can be done before the `OnAfterRenderAsync` stage, when JavaScript interop is available.

As I said, this may be my misunderstanding of the lifecycle of Blazor components, and if so, this can be closed with no action. But it does seem that JS calls have the possibility to made too early here.

**Comment by dvoituron** [comment] 2024-09-19 12:41
@ApacheTech Can you give us a concrete example of how to reproduce this error?
Your code doesn't contain `ThreeState="true"` while you're talking about the intermediate state and you code contains unknown `AvailableServices`, `IsChecked` and `ToggleChecked` methods.

**Comment by ApacheTech** [comment] 2024-09-19 16:27
Whether or not it is three-state or not is irrelevant.

```
<FluentCheckBox @bind-Value="_value" Label="Example" />

@code
{
    private bool _value;
}
```

Using this example:

1. The initial value is set to `bool.TrueString` within [https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Checkbox/FluentCheckbox.razor](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Checkbox/FluentCheckbox.razor), and the `oncheckedchange` event handler is set to `OnCheckedChangeHandlerAsync`.

2. We bind the value to `_value` within our markup within the pre-render stage of our component's lifecycle, using `InteractiveServer`.

3. This immediately calls `OnCheckedChangeHandlerAsync` because the value has changed from true to false.

4. In both a [two-state](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Checkbox/FluentCheckbox.razor.cs#L218), and [three-state](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Checkbox/FluentCheckbox.razor.cs#L101) checkbox, `OnCheckedChangeHandlerAsync` eventually calls `SetIntermediateAsync`.

5. `SetIntermediateAsync` invokes the `JSRuntime` to call [`setFluentCheckBoxIndeterminate`](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Checkbox/FluentCheckbox.razor.cs#L130)

All of this can happen before the page has been rendered, and therefore, before the JSRuntime has access to the DOM.

**Comment by oneolddev** [comment] 2024-09-19 16:46
I believe there is a combination of things interacting here. When I look at the [source code for `fluent-checkbox`](https://github.com/microsoft/fluentui/blob/master/packages/web-components/src/checkbox/checkbox.ts), it is `Observable`, So there is a possibity of a _race condition_ occuring. This could be an explanation for what @ApacheTech is seeing.

BTW - I have been trying to reproduce this problem and have had no success.

**Comment by ApacheTech** [comment] 2024-09-19 16:49
I have streamlined my initial post, to remove any cross-talking with the other issue that has now been resolved.

**Comment by dvoituron** [comment] 2024-09-20 09:36
> I have been trying to reproduce this problem and have had no success. Even an intermittently reproducible sample would be helpful.

Yes, I was unable to reproduce this problem. We need a code example (GitHub) to generate this error. Normally, `@oncheckedchange` should only be triggered once the HTML page has been rendered. So when the DOM is accessible. But perhaps a special case has been omitted. It would be easy to avoid this error, but the HTML and C# state would be different, and we don't want that.

Without being able to reproduce the problem, we can't correct it :-(

**Comment by ApacheTech** [comment] 2024-09-20 11:10
My question plainly stated that I may have misunderstood the lifecycle of the components, multiple times.

This is theoretical conversation.

The "sample" code is your code. In your repos. That I've linked to. In as many places as I can.

There is nothing to reproduce. I have laid out the theory of it in as plain and step-by-step fashion as I possibly can.

I have walked though every step within the code flow.

I have asked whether or not I am correct within my assumptions, and my assessment of how your code works.

I don't know what more I can do.

The only code you need is

```
<FluentCheckBox @bind-Value="_value" Label="Example" />

@code
{
    private bool _value;
}
```

That's it.
That's all there is.

Everything else is asking questions about the exact way that this exact code works within a pre-rendered interactive server app.

**Comment by ApacheTech** [comment] 2024-09-20 11:46
For example, am I misreading the way that the `JSRuntime` is being used? Does it render a script with the `.js` file to the DOM, and then use that script. Or is it all in memory; essentially using it akin to NodeJS? Does `"./_content/Microsoft.FluentUI.AspNetCore.Components/Components/Checkbox/FluentCheckbox.razor.js"` ever even touch the client?

**Comment by vnbaaij** [comment] 2024-09-20 13:16
As Denis (@dvoituron) mentioned: 
> Normally, @oncheckedchange should only be triggered once the HTML page has been rendered. So when the DOM is accessible. 

I don't think there is an error with the code we have now. We would have had way more issues created about this then.


> For example, am I misreading the way that the `JSRuntime` is being used? Does it render a script with the `.js` file to the DOM, and then use that script. Or is it all in memory; essentially using it akin to NodeJS? Does `"./_content/Microsoft.FluentUI.AspNetCore.Components/Components/Checkbox/FluentCheckbox.razor.js"` ever even touch the client?

Yes, a script gets rendered and downloaded to the client. You can see this easily in the browser's DevTools:
![image](https://github.com/user-attachments/assets/26103e4e-256c-4f8c-9108-8a1678e35b7f)

I'm closing this one as there is nothing actionable for us for now.

**Closed by vnbaaij** 2024-09-20 13:16 UTC
Labels: Not reproducible
