### ISSUE TITLE
fix: Icon throws exception when deployed to Azure

### ISSUE THREAD

**Issue by MatejMa2ur** [microsoft/fluentui-blazor#776] opened 2023-09-24 19:21 UTC
In my code I am not even using component with this icon.
It seems like it is being used in ToastService or some other service directly in the package.
If you have some workarounds, feel free to suggest me what should I do.

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type Microsoft.Fast.Components.FluentUI.CoreIcons+Regular+Size24+Dismiss must have a parameterless constructor.
System.ArgumentException: The type Microsoft.Fast.Components.FluentUI.CoreIcons+Regular+Size24+Dismiss must have a parameterless constructor.
   at Microsoft.Fast.Components.FluentUI.FluentIcon`1[[Microsoft.Fast.Components.FluentUI.CoreIcons.Regular.Size24.Dismiss, Microsoft.Fast.Components.FluentUI, Version=3.0.23198.21, Culture=neutral, PublicKeyToken=null]].OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

**Comment by dvoituron** [comment] 2023-09-24 19:33
This exception is raised because, by default, Blazor WebAssembly performs Intermediate Language (IL) trimming to reduce the size of the published output. By default, trimming occurs when publishing an app.
See https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-trimmer

We'll check that this `Regular.Size24.Dismiss` icon is correctly installed to avoid an invalid trimming process during this publication.

In the meantime, can you add this code (even made invisible), to force the compiler to "know" this icon?
And tell us if it solves the problem.

```xml
<FluentBadge Appearance="Appearance.Accent">My badge</FluentBadge>
```

**Comment by MatejMa2ur** [comment] 2023-09-24 19:48
Yes this "fix" is working, and it is not throwing errors 👍

**Comment by dvoituron** [comment] 2023-09-24 19:51
Perfect. So I think I know what the problem is in the library code. We'll fix it as soon as possible.

**Comment by MatejMa2ur** [comment] 2023-09-24 19:59
Should I close this issue?

**Comment by vnbaaij** [comment] 2023-09-24 20:01
No, please leave it open so we get a reminder to fix. We will close it when done.

**Comment by dvoituron** [comment] 2023-09-24 20:01
Keep it open until we update the code. We'll come back here to link this problem to the PR.

**Comment by MatejMa2ur** [comment] 2023-09-24 20:02
Thank you 😊

**Closed** 2023-09-26 11:41 UTC
