### ISSUE TITLE
feat: allow FluentDialogHeader/Footer outside of FluentDialog

### ISSUE THREAD

**Issue by shark0151** [microsoft/fluentui-blazor#3054] opened 2024-12-15 15:22 UTC
# 🙋 Feature Request

Allow the FluentDialogHeader and FluentDialogFooter to be used in any component without having to necessarily be in a Dialog

## 🤔 Expected Behavior
You open an component that has a FluentDialogFooter (not as a dialog) and it works

## 😯 Current Behavior
You open an component that has a FluentDialogFooter (not as a dialog) and it throws error
"Unhandled exception rendering component: FluentDialogFooter must be used inside FluentDialog (Parameter 'Dialog')
      System.ArgumentNullException: FluentDialogFooter must be used inside FluentDialog (Parameter 'Dialog')..."

## 💁 Possible Solution
If possible, to not throw error and just display the footer

## 🔦 Context
Imagine that you have a component that is meant to be open either as a dialog or as a normal component.
With the current implementation I have to check if an instance of Dialog exists and have two versions of the footers that do the same thing. That, or have just my own custom footer, and disable the FluentDialogFooter. 
So then, what is the point of using the fluent footer?
In the SimpleDialog as component example, it shows the component but without the buttons. If the buttons actually do something then it's not a very useful feature.

## 💻 Examples
![Image](https://github.com/user-attachments/assets/9f5e47db-694f-4250-8620-bd16fe8b564e)

**Comment by dvoituron** [comment] 2024-12-15 21:16
It's actually by design: the `FluentDialogFooter` and `FluentDialogHeader` components must be present in the **FluentDialog**.

It's not possible to separate them, mainly because they need a reference to the **FluentDialog** to have the button labels (`PrimaryAction` and `SecondaryAction`) and to call the **Close** and **Cancel** actions of the Dialog box.

**Comment by shark0151** [comment] 2024-12-16 10:40
If you manually declare the header/footer is it not with the intent to override the default? Meaning, whatever action(s) will be manually bound anyway. 

Feels like an arbitrary restriction. I guess I'll just disable them. Would be nice if there was a parameter in the provider for that :)

**Comment by dvoituron** [comment] 2024-12-16 10:45
Behind these components we find the management of the default **FluentDialog** Buttons (Primary and Secondary). Even if, in your case, you don't use these buttons by default. And it's not possible to disable them. 
This **FluentDialogFooter** is only useful if you're in a **FluentDialog**.

Otherwise, the only solution is to add a test in your code to use this Footer or to use your custom buttons. As I think you're already doing.

**Comment by shark0151** [comment] 2024-12-16 11:01
Oh, I meant disable the footer entirely and just use my own. 
You can remove the buttons from the dialog footer if you set the labels to null. And if both are null, then the footer is gone. There isn't an explicit way to remove the footer, but I suppose that it is logical enough. 

Thanks for the clarification

**Comment by vnbaaij** [comment] 2024-12-16 11:19
We operate under the assumption that a dialog always have a header and a footer. You can 
1) change how those look/operate by providing your own code for them. See for example https://www.fluentui-blazor.net/Dialog#customizeddialog. If you add your own buttons, you can add your own logic there as well.

2) override parts of the default display by not showing a primary, secondary or close button, have an icon in the title, etc

Closing this as I think it is not really an issue but more about unclarity of how to use some parts. Please reopen if we misunderstood that.

**Closed by vnbaaij** 2024-12-16 11:19 UTC
Labels: closed:not-actionable
