### ISSUE TITLE
docs: fix/add How to set the width of menu items in FluentMenu 

### ISSUE THREAD

**Issue by JarJasAskom** [microsoft/fluentui-blazor#2747] opened 2024-10-02 08:43 UTC
Menu has long item labels and looks like this:

![image](https://github.com/user-attachments/assets/e04a475c-cf23-4279-8c7e-aec01c999971)

Seting Width property of FluentMenu only moves menu to the left from the button but it does not change its Width. Labels are still overwritten.

Menu item label has slot part like this
```
    <FluentMenuItem OnClick="OnCreateMeteringPoint">
        Utwórz charakterystykę punktu pomiarowego <span slot="end">(proces 2.1)</span>
    </FluentMenuItem>
```
but removing span/slot part does not help if the whole label is long enough.

**Comment by vnbaaij** [comment] 2024-10-02 09:16
@JarJasAskom you know the drill by now...
Please supply us with ready-to-run reproduction code in the form of something we can copy/paste, a (zipped) project structure or a GitHub repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will be closed in **3** days

Help us to help you. Thanks.

**Comment by JarJasAskom** [comment] 2024-10-02 10:43
Create new test application:

dotnet new fluentblazor --name MyApplication

Open file Home.razor, remove its content and paste this:

```
@page "/"
@rendermode InteractiveServer

<FluentButton Id="btn-master-menu"
              Appearance="Appearance.Outline"
              IconEnd="@(new Icons.Filled.Size24.CaretDown())"
              Style="min-width:5em;">
    Procesy CSIRE
</FluentButton>

<FluentMenu Id="master-menu-options" Anchor="btn-master-menu" Trigger="MouseButton.Left" Anchored="true" UseMenuService="false" Width="1000px">
    <FluentMenuItem>
        <ChildContent>
            Wysłanie przez OSD do SE historycznych danych pomiarowo-rozliczeniowych <span slot="end">(11)</span>
        </ChildContent>
        <MenuItems>
            <FluentMenuItem>
                Wysłanie przez OSD do SE historycznego dobowego profilu zużycia <span slot="end">(11.1)</span>
            </FluentMenuItem>
        </MenuItems>
    </FluentMenuItem>
</FluentMenu>
```
The result: menu item does not have width 1000px and/or does not wrap long lines.

![image](https://github.com/user-attachments/assets/9e879da8-8c0b-48f6-af0b-e0e41734d4dc)

**Comment by dvoituron** [comment] 2024-10-02 13:03
By design the `fluent-menu` web component has a `min-width: 64px; max-width: 368px;`.

You can update the maximum width by using a style like this in your code:

```html
<style>
fluent-menu {
    max-width: 1000px;
}
</style>
```

**Closed** 2024-10-02 13:03 UTC
Labels: status:needs-investigation
