### ISSUE TITLE
fluent-nav-text during Desktop view vs Mobile 

### ISSUE THREAD

**Issue by sebastianolafhandjojo** [microsoft/fluentui-blazor#1210] opened 2023-12-26 15:55 UTC
# 🐛 Bug Report

## 😯 Current Behavior and how to produce the bug
1) use the provided template , and open the solution in "Desktop View"
2) click the hamburger menu so it will be in collapse position (only icon appear, no text visible)
3) on Dev tools, change the view from "Desktop View" to "Mobile View"
4) check the Menu, the text will disappear, only Icon appear,  this is unexpected behavior

## 🤔 Expected Behavior
during "Mobile View" the text menu should appear side by side with the icon

## 💻 Repro or Code Sample
root cause is in this file

src\Core\Components\NavMenu\FluentNavMenu.razor.css 
line: 91

/* collapsed */
::deep.collapsed .fluent-nav-text {
    display: none;
}

Since this is related to design.
We will let repo owner take the decision.
We think it should be ok just use "display" anything other than : "none"

[video of proof](https://youtu.be/uvKBEwXiqcg)

**Comment by vnbaaij** [comment] 2023-12-26 22:42
Duplicate of #1183

**Closed by vnbaaij** 2023-12-26 22:42 UTC
Labels: closed:duplicate
