### ISSUE TITLE
Error when running the MAUI Blazor Fluent App (FluentDesignTheme.razor.js file is not moving to the directory .Deploy and run error ,eventhough deploy is configured in the configuration manager).

### ISSUE THREAD

**Issue by VijayakumarKothapalle** [microsoft/fluentui-blazor#2015] opened 2024-05-06 18:03 UTC
Procedure:
As Mentioned in the Code Setup , I have implemented the same in my MAUI project
 
![image](https://github.com/microsoft/fluentui-blazor/assets/122955542/2c1afc43-c950-45a1-b692-5add4d647257)

And in Program.cs
 
![image](https://github.com/microsoft/fluentui-blazor/assets/122955542/426dbacc-f485-4f06-965a-a47765506506)
Issue :
But during Build and running , I am getting this error,”The project needs to be deployed before we can debug .please enable deploy in the configuration manager”  and “DirectoryNotFoundException - Could not find a part of the path … \DesignSystemProvider\FluentDesignTheme.razor.js”
![image](https://github.com/microsoft/fluentui-blazor/assets/122955542/79cc7b87-f20c-42f2-aaaf-bf84a1ed8cf1)

My Project is already configured for build and deploy 
![image](https://github.com/microsoft/fluentui-blazor/assets/122955542/a35ceab0-88bb-4c14-9967-d47865109aa0)

And also Referred [MAUI Project can not import web-components script automatically · Issue #404 · microsoft/fluentui-blazor · GitHub](https://github.com/microsoft/fluentui-blazor/issues/404) for implementation. But unable to find HostingModel in options and FileBasedStaticAssetService in package.

![image](https://github.com/microsoft/fluentui-blazor/assets/122955542/a320f25f-de11-41e6-adab-63eb3ba28623)

Could you please help on this issue and give detailed configuration for MAUI.

**Comment by vnbaaij** [comment] 2024-05-09 16:30
You have not specified which version of the library you are using. But the code you posted is for version 2 and won't work with v3/v4
You don't need any other setup as described in our docs.
Closing this as no reproduction code is provided and we can't reproduce.

**Closed** 2024-05-09 16:31 UTC
Labels: closed:not-actionable
