### ISSUE TITLE
fix: FluentBadge content alignment when component is static

### ISSUE THREAD

**Issue by swegele** [microsoft/fluentui-blazor#1749] opened 2024-03-27 16:48 UTC
Love the controls!!

# 🐛 Bug Report
Counter page FluentBadge alignment is skewed when page is rendered statically

**SERVER and WASM INTERACTIVE:**
![GoodLabel with ServerInteractive](https://github.com/microsoft/fluentui-blazor/assets/6868671/3d858cae-b365-44ac-95e4-63464a9ccbc0)

**STATIC:**
![BadLabel with ServerInteractive](https://github.com/microsoft/fluentui-blazor/assets/6868671/340f876d-2984-40f4-bc16-8f34d78d4a69)

## 💻 Repro or Code Sample

1. Create Project "Auto" - mode declared on each page
2. Create a copy of Counter.razor and call it CounterStatic.razor.
3. Change route to "\counter_static"
4. At top of page delete /@rendermode line to make it static
5. Add to NavMenu
6. Run and navigate

## 🤔 Expected Behavior
All 3 render modes should look the same

## 😯 Current Behavior
Static is different
Upon inspecting elements, it looks like the "0" div ends up outside the badge container.

## 🔦 Context
Latest version of controls/nuget

**Comment by c0g1t8** [comment] 2024-03-27 20:14
## InteractiveAuto rendermode
![image](https://github.com/microsoft/fluentui-blazor/assets/23250332/a33641ae-060c-4fdf-87d2-77286f8a2e91)

## no rendermode specified 
![image](https://github.com/microsoft/fluentui-blazor/assets/23250332/f55ff931-e4ef-48b0-b6c1-e9c14cc7de4e)

**Comment by vnbaaij** [comment] 2024-03-27 20:49
So the div that contains the content is not placed in the shadow DOM in SSR mode. I don't think that's really strange but also don't know yet why that is the case. 

@swegele 's assumption that all 3 render modes should look the same is a nice one but not necessariy true in practice. We have not claimed anywhere that all components work in SSR mode.

**Comment by swegele** [comment] 2024-03-27 21:06
I actually thought about if the lack of interactivity here was logical (example: obviously the button doesn't do anything but that is expected).  Couldn't think of a reason why it would render differently....so just passing it on.   😃 

Thanks again for your work on this.  I'm adopting it in upcoming projects.

**Comment by swegele** [comment] 2024-03-28 01:25
@vnbaaij I just noticed something that maybe gives a hint.  I deleted cache and loaded a counter page set for:
`@rendermode InteractiveWebAssembly` - thus it had a delay while loading the WASM (few seconds).  While it was loading the div with "0" was underneath like in the screenshots in previous comments.  But when the WASM loaded then the "0" value popped up where it was supposed to be.  

So it does look like the "div" tag literally gets moved **inside** the badge component during subsequent rendering.

**Comment by c0g1t8** [comment] 2024-03-28 01:27
It looks like the issue is in the underlying `fluent-badge` web component. Working on the repro now.

**Comment by c0g1t8** [comment] 2024-03-28 17:01
@swegele 

> @vnbaaij I just noticed something that maybe gives a hint. I deleted cache and loaded a counter page set for: `@rendermode InteractiveWebAssembly` - thus it had a delay while loading the WASM (few seconds). While it was loading the div with "0" was underneath like in the screenshots in previous comments. But when the WASM loaded then the "0" value popped up where it was supposed to be.
> 
> So it does look like the "div" tag literally gets moved **inside** the badge component during subsequent rendering.

The _flicker_ you are seeing is the transition from the initial static rendering generated by the server to the rendering generated by Blazor. All the interactive modes of **Blazor Web Apps** initially do a static render. This issue makes it more visually apparent.

**Comment by swegele** [comment] 2024-03-28 17:13
> The flicker you are seeing is the transition from the initial static rendering generated by the server to the rendering generated by Blazor. All the interactive modes of Blazor Web Apps initially do a static render. This issue makes it more visually apparent.

I downloaded the source and took a gander.  I was unable to determine why it would ever render content outside the <fluent-badge> tag.  

_P.S.  I also realized how there are some very smart people out there!  This is very well organized code with tests and auto-documenting etc.  A little above my head too!

**Comment by c0g1t8** [comment] 2024-03-28 17:24
It appears the underlying issue is in the **fluent-badge** web component. If the **fluent-badge** component is enclosed in a _p tag_, this issue appears. The issue doesn't appear when enclosde in a _div tag_.

## Repro
### Code
``` razor
@page "/staticcounter"
@* @rendermode InteractiveAuto *@

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: <FluentBadge Appearance="Appearance.Neutral">@currentCount</FluentBadge></p>

<FluentButton Appearance="Appearance.Accent" @onclick="IncrementCount">Click me</FluentButton>

<hr />

<h2>Repro</h2>

<p>Explicitly using fluent-badge</p>

<h3>Original</h3>
<p>
    Test #1:
    <fluent-badge>
        <div>@currentCount</div>
    </fluent-badge>
</p>

<h3>Workaround</h3>
<div>
    Test #2:
    <fluent-badge>
        <div>@currentCount</div>
    </fluent-badge>
</div>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;
    }
}
```
### Results
![image](https://github.com/microsoft/fluentui-blazor/assets/23250332/48ec6eb9-adcb-40f7-b4e9-ab5b29272a5f)

As to why this only doesn't appear when not statically rendered, I suspect it has something to do with the way Blazor DOM is created.  I'm guessing the leaf nodes are created first. 

@vnbaaij Is this a **fluent-badge** bug?

**Comment by c0g1t8** [comment] 2024-03-28 18:08
The workaround would be replacing
``` razor
<p role="status">Current count: <FluentBadge Appearance="Appearance.Neutral">@currentCount</FluentBadge></p>
```
with
``` razor
<div role="status" style="padding-bottom: 1em;">
    Current count: <FluentBadge Appearance="Appearance.Neutral">@currentCount</FluentBadge>
</div>
```

**Comment by vnbaaij** [comment] 2024-03-28 19:03
Great find Gary!

I'm not sue if this is really a web component bug. 

Looking at the source at https://github.com/microsoft/fast/tree/archives/fast-element-1/packages/web-components/fast-foundation/src/badge, I can only conclude that this is about the simplest webcomponent of all of them. And besides, the web component has no influence on what it is surrounded with so I'm more inclined to think it is actually a Blazor thing.

**Comment by vnbaaij** [comment] 2024-03-28 19:20
I implemented the replacing of the `p` with a `div` in the template code. Will be in next release.

As we have a workaround whit that, I'm closing this one for now.

**Comment by swegele** [comment] 2024-03-28 19:21
thanks to you both!

**Comment by c0g1t8** [comment] 2024-03-28 22:17
@vnbaaij 

I was able to recreate the issue outside of Blazor in [Codepen](https://codepen.io/c0g1t8/pen/bGJopbb).

![image](https://github.com/microsoft/fluentui-blazor/assets/23250332/8ad6dbad-bd38-467e-83ec-6bc1155e4250)

**Comment by vnbaaij** [comment] 2024-03-28 22:23
Will you create an I Zschopau it in the Fluent UI repo?

**Comment by c0g1t8** [comment] 2024-04-10 17:13
@vnbaaij 

Given that I filed this as an [issue in the fluentui repo](https://github.com/microsoft/fluentui/issues/30905), can we re-open this and add labels `area:fluent-ui-web-components` and `status:blocked`?

**Comment by vnbaaij** [comment] 2024-04-23 21:44
Update on this one...I spoke with the Fluent team and it looks like the cause of this is using a div (which is a block element) into an inline element. An easy workaround is to use a span element inside the FluentBadge or, even better, don't wrap the text at all. 
So approach to solve is: 
1. Don't wrap it, just pass the text...you don't need that div. Updated to illustrate that.
2. Use an inline element like span
3. Style the div to be an inline element

You can verify this works by altering the codepen link provided earlier. Also add `appearance="accent"` to the fluent-badge tags to make them better visible:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/f2d3d81d-c1cc-4a14-a262-113883af749e)


Closing this as a good workaround is now available.

**Closed by vnbaaij** 2024-04-23 21:44 UTC
Labels: area:fluent-ui-web-components, status:blocked

**Comment by MaRRiK74** [comment] 2024-05-24 08:08
@vnbaaij 

When using HorizontalPosition and/or VerticalPosition it still has an issue

`<FluentCounterBadge Count="counter" Appearance="Appearance.Lightweight" HorizontalPosition="0" VerticalPosition="0">
    <FluentButton Appearance="Appearance.Accent" OnClick="@Increment">
        <FluentIcon Value="@(new Icons.Regular.Size24.Alert())" Color="@Color.Fill" />
    </FluentButton>
</FluentCounterBadge>

@code {
    int counter = 1;

    public void Increment()
    {
        counter++;
    }
}`

![Badge](https://github.com/microsoft/fluentui-blazor/assets/19833001/e8cd470e-58cc-4607-8a15-dd2c6e59e5c0)
