### ISSUE TITLE
RawEventHandlers fluent-menu-item has error

### ISSUE THREAD

**Issue by zandiarash** [microsoft/fluentui-blazor#2549] opened 2024-08-18 12:27 UTC
There is an error in **RawEventHandlers.razor** file which prevents to run.
![bug](https://github.com/user-attachments/assets/eb33b277-791f-493f-8ffb-7a49d9ad1cef)

**Comment by dvoituron** [comment] 2024-08-18 13:55
I don't understand why you're getting an error on this attribute. `role` is a `string` attribute, so you can place any string you like.

On the other hand, we don't have this error with the latest version of Visual Studio Preview.
Which version are you using? Which version of .NET?

**Comment by zandiarash** [comment] 2024-08-18 18:30
> I don't understand why you're getting an error on this attribute. `role` is a `string` attribute, so you can place any string you like.
> 
> On the other hand, we don't have this error with the latest version of Visual Studio Preview.
> Which version are you using? Which version of .NET?

I am using Dotnet 9 and Visual studio the latest preview version.

**Comment by zandiarash** [comment] 2024-08-19 05:12
> I don't understand why you're getting an error on this attribute. `role` is a `string` attribute, so you can place any string you like.
> 
> On the other hand, we don't have this error with the latest version of Visual Studio Preview. Which version are you using? Which version of .NET?

I cloned again the **dev** branch it has this error yet
![image](https://github.com/user-attachments/assets/6957c6fb-0c40-4123-b394-88bd6429f3c0)

**Comment by dvoituron** [comment] 2024-08-19 05:19
Can you try to build using DotNet8 (and not 9)?

**Comment by zandiarash** [comment] 2024-08-19 05:24
> Can you try to build using DotNet8 (and not 9)?

I tried **dotnet build --framework net8.0** error still exists.

**Comment by vnbaaij** [comment] 2024-08-22 20:31
This is caused by an error in your environment, not by an issue in the library/code. Another thing you can try is to add a `global.json` file to the root of your repo folder containing the following:

```
{
  "sdk": {
    "version": "8.0.302",
    "rollForward": "major"
  }
}
```

Closing this as it can't be solved from our side.

**Closed by vnbaaij** 2024-08-22 20:31 UTC
Labels: needs: author feedback
