### ISSUE TITLE
fix: [FluentNumberField Validation] in [EditForm]

### ISSUE THREAD

**Issue by Invop** [microsoft/fluentui-blazor#1788] opened 2024-04-03 16:09 UTC
# 🐛 Bug Report

https://www.fluentui-blazor.net/Forms

if in the field <FluentNumberField Name="accomodation" @bind-Value="starship.MaximumAccommodation" Label="Maximum Accommodation" Required /

If you enter floating point values by mistake and then delete and write the correct int value, the field fails validation

![image](https://github.com/microsoft/fluentui-blazor/assets/96420885/e6db81ee-c185-40ef-9ed2-a1492aeadecf)
![image](https://github.com/microsoft/fluentui-blazor/assets/96420885/354a70b2-0c5e-424f-acb2-4f4bf3aceb55)

* OS & Device: [Windows] on [PC]
* Browser [Google Chrome]

**Comment by vnbaaij** [comment] 2024-04-03 17:01
Duplicate of #1345

**Closed** 2024-04-03 17:01 UTC
Labels: closed:duplicate
