### ISSUE TITLE
FluentMenu (placed on the end of page) - Page content is resizing each time menu is opening

### ISSUE THREAD

**Issue by gryzorr** [microsoft/fluentui-blazor#2379] opened 2024-07-15 11:46 UTC
# 🐛 Bug Report

When FluentMenu is place on right side of the page then content is resizing causing scrollbars to show and hide.

## 💻 Repro or Code Sample

Nothing special in code, see video.

## 🤔 Expected Behavior

Openned menu without page flickering.

## 😯 Current Behavior

Page flickering because of scrollbars showing/disappearing.

## 💁 Possible Solution

It would be nice have the same solution like in FluentProfileMenu (there was similar problem).

## 🔦 Context

Minor problem but nice to have.

## 🌍 Your Environment
* OS & Device: Windows
* Browser: Microsoft Edge, Google Chrome
* .NET and Fluent UI Blazor library Version: 4.9.1

https://github.com/user-attachments/assets/0a135327-2103-4fe2-88d2-d6b584d1b25c

**Comment by dvoituron** [comment] 2024-07-15 11:55
Without a code example to reproduce this problem, we can't do anything.
Can you provide us with such an example?

Have you configured your HTML `body' style as described in the documentation: https://www.fluentui-blazor.net/DesignTheme

```css
body {
    margin: 0;
    padding: 0;
    height: 100vh;   👈
    font-family: var(--body-font);
    font-size:   var(--type-ramp-base-font-size);
    line-height: var(--type-ramp-base-line-height);
    font-weight: var(--font-weight);
    color:       var(--neutral-foreground-rest);
    background:  var(--neutral-fill-layer-rest);
}
```

**Comment by gryzorr** [comment] 2024-07-15 12:05
[app.zip](https://github.com/user-attachments/files/16234186/app.zip)
We have generated app from Fluent UI App Template but probably it evolves. Here is our app.css file.

**Comment by vnbaaij** [comment] 2024-07-15 12:10
What do you expect us to do with this file? 
- Create a site from demo,
- then paste in your file, 
- try to come up with code that reproduces the issue
- ...
I hope you understand that that is not workable for us. You need to supply us with actual reproduction code. If you can't share your project because of whatever reason, that is fine. You then create a minimal project that does reproduce the issue and supply that to us.

Help us to help you. Thanks.

**Comment by vnbaaij** [comment] 2024-07-23 19:45
No community interest. Closing.

**Closed by vnbaaij** 2024-07-23 19:45 UTC
Labels: community:good-first-issue, community:contribution
