### ISSUE TITLE
fix: FluentTreeView events not called for Windows Forms, BlazorWebView component

### ISSUE THREAD

**Issue by hml-coder** [microsoft/fluentui-blazor#633] opened 2023-08-20 22:39 UTC
# 🐛 Bug Report

No FluentTreeview events called when using Windows Forms project with BlazorWebView  hosting razor component from RCL

## 💻 Repro or Code Sample

Manually downloaded web-components-v2.5.16.min.js but that did not resolve the issue.  

The OnClick event for the FluentButton works in this environment.

I'm very new to Blazor and FluentUI so maybe I'm missing something.

`<PackageReference Include="Microsoft.Fast.Components.FluentUI" Version="3.0.0-RC.1" />`

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Notifications</title>
    <base href="/" />
    <link href="_content/Microsoft.Fast.Components.FluentUI/css/reboot.css" rel="stylesheet" />
    <link href="css/app.css" rel="stylesheet" />
    <link href="Hml.SysTray.Notifications.styles.css" rel="stylesheet" />
</head>

<body>

    <div id="app">Loading...</div>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>s
        <a class="dismiss">🗙</a>
    </div>

    <script type="module" src="js/web-components-v2.5.16.min.js"></script>

    <!--<script type="module" src="_content/Microsoft.Fast.Components.FluentUI/js/web-components.min.js"></script>-->
    <!--<script type="module" src="_content/Microsoft.Fast.Components.FluentUI/js/web-components-v2.5.16.min.js"></script>-->

    <script src="_framework/blazor.webview.js"></script>

</body>
</html>
```

![image](https://github.com/microsoft/fluentui-blazor/assets/63738138/77249ede-c470-4f94-86b0-60aee1500208)

## 🌍 Your Environment

* OS & Device: Windows
* Browser : FireFox
* .NET and FAST:  net7.0-windows, 3.0.0-RC.1

**Comment by vnbaaij** [comment] 2023-08-21 12:26
Hi Roland,

Let me try to explain what is happening. Some web components (such as the fluent-tree-view) generate custom JavaScript events when user interaction with the component is taking place. These events are 'captured' on the Blazor side and become available on the Balzor components in the form of the `@onselectedchange` etc. This is just standard Blazor functionality as described in https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-7.0#custom-event-arguments.
As can be seen in that article, the events  need to be hooked up in the `afterStarted` method in the [JavaScript initializers](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0#javascript-initializers)

The issue is that when using the WebView the library's script does not get called so the `registerCustomEventType` methods do not get called which leads to the custom events not being picked up and handeled by Blazor.

I have not had time yet to find out if/how the initialization can be done when the WebView is being used.

**Comment by vnbaaij** [comment] 2023-08-21 12:35
On the web-components script file...

Starting with version 2.4.2, we added a version part to the (automatically loaded) web components script. So it will show up, in DevTools for example
`<script type="module" src="_content/Microsoft.Fast.Components.FluentUI/js/web-components-v2.5.16.min.js"></script>`
Versions before will still have 
`<script type="module" src="_content/Microsoft.Fast.Components.FluentUI/js/web-components.min.js"></script>`

In v3 we will also add this version part to the script **BUT** that has not been done yet for the RC1 version/package. Any newer versions will have the version appended.

Hope this clears up some confusion..,

**Comment by vnbaaij** [comment] 2023-08-21 13:25
I've already reached out internally but guess it would make sense to log an issue in the ASP.NET Core repo. Would be great if you can do that.

**Comment by vnbaaij** [comment] 2023-08-21 13:29
Wait, I suddenly remembered we already ran into this with MAUI and, more importantly, we have a workaround!! See https://github.com/microsoft/fluentui-blazor/issues/404
As mentioned in that issue, an issue on the ASP.NET Core repo has already been raised. Please add to what is already described there.

**Comment by vnbaaij** [comment] 2023-08-21 13:57
Closing this as using the workaround as described in #404 works. Confirmed it on your minimal test case included earlier

**Closed by vnbaaij** 2023-08-21 13:57 UTC
