### ISSUE TITLE
FluentNumberField with ReadOnly Attribute Sometimes Fails to Track Display Data Correctly

### ISSUE THREAD

**Issue by Sweetli1415926** [microsoft/fluentui-blazor#2890] opened 2024-10-30 15:06 UTC
# 🐛 Bug Report

## 💻 Repro or Code Sample

I modified a default sample of Fluent Blazor Web App for the Counter page as follows:

```
@page "/counter"
@inject SharedService SharedService
<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<div role="status" style="padding-bottom: 1em;">
    Current count: <FluentBadge Appearance="Appearance.Neutral">@SharedService.currentCount</FluentBadge>
    <FluentNumberField HideStep="true" @bind-Value=@SharedService.currentCount ReadOnly />
</div>

<Test UpdateUI="UpdateUI"></Test>

@code {
    private void UpdateUI()
    {
        StateHasChanged();
    }
}
I added a child component <h3>Test</h3>:

razor

@inject SharedService SharedService

<FluentNumberField HideStep="true" TValue="int" Value=@a ValueChanged="@((newValue)=>CellEndEdit("a", newValue))" />
<FluentNumberField TValue="int" HideStep="true" Value=@b ValueChanged="@((newValue)=>CellEndEdit("b", newValue))" />

@code {
    [Parameter]
    public EventCallback UpdateUI { get; set; }
    int a = 0;
    int b = 0;

    private async Task CellEndEdit(string name, object? newValue)
    {
       @page "/counter"
@inject SharedService SharedService
<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<div role="status" style="padding-bottom: 1em;">
    Current count: <FluentBadge Appearance="Appearance.Neutral">@SharedService.currentCount</FluentBadge>
    <FluentNumberField HideStep="true" @bind-Value=@SharedService.currentCount ReadOnly />
</div>

<Test UpdateUI="UpdateUI"></Test>

@code {
    private void UpdateUI()
    {
        StateHasChanged();
    }
}
I added a child component <h3>Test</h3>:

razor

@inject SharedService SharedService

<FluentNumberField HideStep="true" TValue="int" Value=@a ValueChanged="@((newValue)=>CellEndEdit("a", newValue))" />
<FluentNumberField TValue="int" HideStep="true" Value=@b ValueChanged="@((newValue)=>CellEndEdit("b", newValue))" />

@code {
    [Parameter]
    public EventCallback UpdateUI { get; set; }
    int a = 0;
    int b = 0;

    private async Task CellEndEdit(string name, object? newValue)
    {
        if (name == "a")
            a = (int)newValue;
        else
            b = (int)newValue;
        SharedService.currentCount = a * b;
        await UpdateUI.InvokeAsync();
    }
}
The SharedService class is defined as:

public class SharedService
{
    public int currentCount { get; set; } = 0;
}
        SharedService.currentCount = a * b;
        await UpdateUI.InvokeAsync();
    }
}
The SharedService class is defined as:

public class SharedService
{
    public int currentCount { get; set; } = 0;
}
```
Steps to Reproduce
Input values 2 and 4 in the FluentNumberField of the <Test.razor> .
The Counter page displays 8 in both controls.
Change the inputs to 2 and 5; the display updates to 10.
Change the values back to 2 and 4; the display shows 8 and 10 instead of both displaying 8.
Important Notes
The issue occurs specifically with the FluentNumberField in the Test component when the values change.
The FluentNumberField in the Counter component, which has the ReadOnly attribute, causes this display issue.
If I remove the ReadOnly attribute from the Counter component's <FluentNumberField HideStep="true" Value=@SharedService.currentCount ReadOnly />, the issue does not occur.
🤔 Expected Behavior
The Counter page should display the correct current count based on the inputs in both cases, regardless of the ReadOnly state.

😯 Current Behavior
![Image](https://github.com/user-attachments/assets/a5a17817-fc49-4f45-a7c3-f0ee525353c5)
![Image](https://github.com/user-attachments/assets/14753bbf-6278-466d-a1ae-af5720470702)
![Image](https://github.com/user-attachments/assets/88a54387-62b5-41c8-a9f4-0b4e3b66ac49)

When the ReadOnly attribute is set in the Counter component, the display does not update correctly when previously entered values are reused.

💁 Possible Solution
It may be worth investigating how the FluentNumberField interacts with ReadOnly mode and whether it affects state changes and UI updates.

🔦 Context
This issue affects the ability to accurately display computed values based on user input, leading to confusion about the current count.

🌍 Your Environment
OS & Device: Windows 10 on PC
Browser: Google Chrome
.NET Version: [8.0.0]
Fluent UI Blazor Library Version: [4.10.3]

**Comment by vnbaaij** [comment] 2024-11-04 11:20
Please fix the reproduction example code.

Not at my pc now, but why use a number input for read-only. You don't gain anything from that. In fact, you are not even able to set a ',' as a separator. Just use TextField

**Comment by vnbaaij** [comment] 2024-11-06 15:42
Hi,

Please make the reproduction code a runable example. Your code is incomplete (service registration) and the rest of the code is all in one block. We do not have capacity to investigate issues in a way where we need to reconstruct and guess. 

Standard reply follows:
Please supply us with ready-to-run reproduction code in the form of something we can copy/paste, a (zipped) project structure or a GitHub repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will be closed in **3** days

Help us to help you. Thanks.

**Comment by vnbaaij** [comment] 2024-11-08 12:25
Closed due to inactivity

**Closed by vnbaaij** 2024-11-08 12:25 UTC
Labels: needs: repro code or repository

**Comment by Sweetli1415926** [comment] 2024-11-08 14:20
I've already pushed the code to GitHub, so you can git clone it here: https://github.com/Sweetli1415926/NumberFieldTest.git. To make it easier, I've also included a screen recording.
https://github.com/user-attachments/assets/19679eba-7171-4dbf-a3c2-0e50369bedd4
Here’s the code:

In Counter.razor:

@page "/"
@inject SharedService SharedService
<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<div role="status" style="padding-bottom: 1em;">
    FluentBadge: <FluentBadge Appearance="Appearance.Neutral">@SharedService.currentCount</FluentBadge>

    ReadOnly:<FluentNumberField HideStep="true" @bind-Value=@SharedService.currentCount ReadOnly />
    WithoutReadOnly:<FluentNumberField HideStep="true" @bind-Value=@SharedService.currentCount />
</div>

<Test UpdateUI="UpdateUI"></Test>

@code {
    private void UpdateUI()
    {
        StateHasChanged();
    }
}
In Test.razor:

@inject SharedService SharedService

<FluentNumberField HideStep="true" TValue="int" Value=@a ValueChanged="@((newValue) => CellEndEdit("a", newValue))" />
<FluentNumberField TValue="int" HideStep="true" Value=@b ValueChanged="@((newValue) => CellEndEdit("b", newValue))" />

@code {
    [Parameter]
    public EventCallback UpdateUI { get; set; }
    int a = 0;
    int b = 0;

    private async Task CellEndEdit(string name, object? newValue)
    {
        if (name == "a")
            a = (int)newValue;
        else
            b = (int)newValue;

        SharedService.currentCount = a * b;
        await UpdateUI.InvokeAsync();
    }
}
here’s my SharedService class:


public class SharedService
{
    public int currentCount { get; set; } = 0;
}
builder.Services.AddScoped<SharedService>();
Thank you for taking a look!

**Comment by NabaviFard-Mahdi** [comment] 2024-11-10 14:11
FluentNumberField dos not update properly when 

TValue:Int
1) Value = 0
2) Change Value to NULL ( Clear Any Number in InputBox) ParsingError has occurs
3) Change Value To 0 , any number. but the ParsingError not Clear and Validation still invalid

i thing this error just in css and classes and thad dos not update properly

![Image](https://github.com/user-attachments/assets/e234e9dc-40e5-41a9-91c5-ca677daea7ff)

**Comment by vnbaaij** [comment] 2024-11-10 14:21
@NabaviFard-Mahdi don't attach new issues to closed issues please. Besides, look through te existing issues. This is a duplicate.
