### ISSUE TITLE
fix: MessageBar Doesn't Respect Theme When using FluentDesignTheme

### ISSUE THREAD

**Issue by AathifMahir** [microsoft/fluentui-blazor#1148] opened 2023-12-18 05:45 UTC
# 🐛 Bug Report

MessageBar Doesn't Respect Theme When using FluentDesignTheme, Even this issue Happens on Fluent UI Blazor Demo Site as Well

## 💻 Repro or Code Sample

https://www.fluentui-blazor.net/MessageBar

## 🤔 Expected Behavior

It should respective the current theme

## 😯 Current Behavior

![image](https://github.com/microsoft/fluentui-blazor/assets/17165402/6679bced-d7e3-41f0-9fe8-bd39038e19bf)

**Comment by vnbaaij** [comment] 2023-12-18 10:45
Hi,

Yes, we still need to tie the theme changing into this component. As this is not a web component based Blazor component, we need to take care of this ourselves...

**Comment by AathifMahir** [comment] 2023-12-19 15:04
> Hi,
> 
> Yes, we still need to tie the theme changing into this component. As this is not a web component based Blazor component, we need to take care of this ourselves...

Any possibile workaround to fix this issue for now? I tried applying the current theme to Tokens as well, that also didn't fixed the issue

**Comment by vnbaaij** [comment] 2023-12-19 16:12
No, no workaround available. We fixed it and it will be in v4.2.1 which is due in a bit (before 🎄)

**Comment by AathifMahir** [comment] 2023-12-19 16:13
> No, no workaround available. We fixed it and it will be in v4.2.1 which is due in a bit (before 🎄)

That's awesome, Thanks for great works

**Comment by vnbaaij** [comment] 2023-12-19 16:20
We just want to solve #1160 and then do release

**Comment by vnbaaij** [comment] 2023-12-20 14:54
Fixed in 4.2.1

**Closed by vnbaaij** 2023-12-20 14:54 UTC

**Comment by AathifMahir** [comment] 2024-01-25 14:48
This issue seems to be happening When the Theme is Set to System, 

![Screenshot_20240125_201749_Chrome.jpg](https://github.com/microsoft/fluentui-blazor/assets/17165402/05f08eec-7c5c-4b09-af5e-adf9309259c0)

**Comment by dvoituron** [comment] 2024-01-31 17:19
@AathifMahir The issue 1182 is related to the "head is currently locked" javascript error.
About this theme issue, I cannot reproduce your screenshot.

![Theme](https://github.com/microsoft/fluentui-blazor/assets/8350694/1a368ae2-9003-4a00-bb93-fd6d34bb8b17)

**Comment by AathifMahir** [comment] 2024-01-31 17:53
> @AathifMahir The issue 1182 is related to the "head is currently locked" javascript error.
> About this theme issue, I cannot reproduce your screenshot.
> 
> ![Theme](https://github.com/microsoft/fluentui-blazor/assets/8350694/1a368ae2-9003-4a00-bb93-fd6d34bb8b17)
> 

The issues happens on current Fluent UI website, I just ran it on my phone, the issue exists.

https://drive.google.com/file/d/1N3wkzrpVTfa33tPS4ladN32X0mhLRzBg/view?usp=drivesdk

**Comment by AathifMahir** [comment] 2024-01-31 18:09
> > @AathifMahir The issue 1182 is related to the "head is currently locked" javascript error.
> > About this theme issue, I cannot reproduce your screenshot.
> > 
> > ![Theme](https://github.com/microsoft/fluentui-blazor/assets/8350694/1a368ae2-9003-4a00-bb93-fd6d34bb8b17)
> > 
> 
> The issues happens on current Fluent UI website, I just ran it on my phone, the issue exists.
> 
> https://drive.google.com/file/d/1N3wkzrpVTfa33tPS4ladN32X0mhLRzBg/view?usp=drivesdk
> 
> 
> Edit: if we set the theme to system again from the theme selector the issue disappears temporarily but if we reload the site again, it happens again

Update:

This issue seems to be fixed with v4.3.2 which does fix the heap lock issue.

No further action needed, Thanks @dvoituron
