### ISSUE TITLE
fix: Invoking Show Confirmation in Dialog Breaks the App in Release Mode

### ISSUE THREAD

**Issue by AathifMahir** [microsoft/fluentui-blazor#1354] opened 2024-01-19 02:44 UTC
Invoking Show Confirmation Dialog on Dialog Service Breaks Production App, This issue doesn't happen when Debugging But Happens on Release Build, When the Issue Happens the Dialog Doesn't Show the Description Anymore but Dialog Pops up

![image](https://github.com/microsoft/fluentui-blazor/assets/17165402/bec476f7-64f8-4058-9188-d8166e898569)

![image](https://github.com/microsoft/fluentui-blazor/assets/17165402/0fc31744-0a69-472a-a883-17ee0f929a69)

Here's the Code that i have used in the sample

```csharp

var dialog = await DialogService.ShowConfirmationAsync(
$"Would you like to Switch the Role from {UserDetails!.Role} to {NewRole}", title: "Switch Role");

var results = await dialog.Result;
if (results is not null && !results.Cancelled)
{
    UserDetails!.Role = role;
    StateHasChanged();
}
```

## 🤔 Expected Behavior

Should Work as Normal

## 💁 Possible Solution

Not Found any workaround as of now.

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Chrome and Edge
* .NET and FAST Version : Tested with 4.2.1 to 4.3.1

**Comment by dvoituron** [comment] 2024-01-19 08:32
Duplicate of #1255

**Closed** 2024-01-19 09:06 UTC
Labels: closed:duplicate

**Comment by vnbaaij** [comment] 2024-01-21 12:46
@AathifMahir please see the steps I took to try to reproduce in #1255
I'm not seeing the error 😕

**Comment by AathifMahir** [comment] 2024-01-21 12:48
> @AathifMahir please see the steps I took to try to reproduce in #1255
> I'm not seeing the error 😕 

Adding this csproj fixed the issue, sorry for missing old issue and creating a duplicate one

```csharp
<ItemGroup> <TrimmerRootAssembly Include="Microsoft.FluentUI.AspNetCore.Components" /> </ItemGroup>
```
