### ISSUE TITLE
How to handle caching issues?

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#2208] opened 2024-06-18 10:38 UTC
Since the library has been updated to v4.8.0 I'm getting this issue for every user who has visited my site before.

```
Unhandled exception rendering component: element.addEventListener is not a function
TypeError: element.addEventListener is not a function
    at Module.RegisterKeyCode (https://hstrend.scholzdom.local/_content/Microsoft.FluentUI.AspNetCore.Components/Components/KeyCode/FluentKeyCode.razor.js:47:17)
    at https://hstrend.scholzdom.local/_framework/blazor.web.js?:1:2894
    at new Promise (<anonymous>)
    at v.beginInvokeJSFromDotNet (https://hstrend.scholzdom.local/_framework/blazor.web.js?:1:2851)
    at vn._invokeClientMethod (https://hstrend.scholzdom.local/_framework/blazor.web.js?:1:65711)
    at vn._processIncomingData (https://hstrend.scholzdom.local/_framework/blazor.web.js?:1:63100)
    at connection.onreceive (https://hstrend.scholzdom.local/_framework/blazor.web.js?:1:56741)
    at i.onmessage (https://hstrend.scholzdom.local/_framework/blazor.web.js?:1:80689)
Microsoft.JSInterop.JSException: element.addEventListener is not a function
TypeError: element.addEventListener is not a function
    at Module.RegisterKeyCode (https://hstrend.scholzdom.local/_content/Microsoft.FluentUI.AspNetCore.Components/Components/KeyCode/FluentKeyCode.razor.js:47:17)
    at https://hstrend.scholzdom.local/_framework/blazor.web.js?:1:2894
    at new Promise (<anonymous>)
    at v.beginInvokeJSFromDotNet (https://hstrend.scholzdom.local/_framework/blazor.web.js?:1:2851)
    at vn._invokeClientMethod (https://hstrend.scholzdom.local/_framework/blazor.web.js?:1:65711)
    at vn._processIncomingData (https://hstrend.scholzdom.local/_framework/blazor.web.js?:1:63100)
    at connection.onreceive (https://hstrend.scholzdom.local/_framework/blazor.web.js?:1:56741)
    at i.onmessage (https://hstrend.scholzdom.local/_framework/blazor.web.js?:1:80689)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.FluentUI.AspNetCore.Components.FluentKeyCode.OnAfterRenderAsync(Boolean firstRender) in /_/src/Core/Components/KeyCode/FluentKeyCode.razor.cs:line 126
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

A quick look to file shows that the browser holds a cached version of this. Is there any easy way to clear the cache globally for this so I don't need to call every user to manually refresh the cache?

**Comment by Lindsay-Mathieson** [comment] 2024-06-18 10:53
Dunno if theres a way to globally force a refresh, but I explicitly set the fluentui package version to 4.7.2 and republished to work around this.

**Comment by Lindsay-Mathieson** [comment] 2024-06-18 10:54
nb. This is being worked on for the next version:

https://github.com/microsoft/fluentui-blazor/issues/2205#issuecomment-2175534972

**Comment by vnbaaij** [comment] 2024-06-18 11:57
Duplicate of #2205

**Closed by vnbaaij** 2024-06-18 11:57 UTC
Labels: closed:duplicate, triage
