### ISSUE TITLE
fix: Can't access content displayed off the screen in FluentPopover

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#1379] opened 2024-01-25 05:42 UTC
# 🐛 Bug Report

It's difficult to access content in a FluentPopover that displays off the bottom of the screen.

## 💻 Repro or Code Sample

This problem can be seen on the popover demo page. If the page is resized so that content is displayed off the the bottom of the page, it isn't possible to scroll with middle-click scrolling or use arrow keys. Clicking on the browser scroll bar hides the popover.

![popover-scrolling](https://github.com/microsoft/fluentui-blazor/assets/303201/bbe9cbe4-8123-4037-9859-46d966fdd918)

The only thing I found that worked is middle clicking on the popover itself and then scrolling. This isn't intuitive.

## 🤔 Expected Behavior

Scrolling should work. Or perhaps the popover show display above the button if there isn't room below.

## 😯 Current Behavior

Can't scroll. Content in popover is hard to access.

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Chrome
* .NET: .NET 8

**Comment by dvoituron** [comment] 2024-01-25 17:19
Indeed, I think it would be interesting to add a `VerticalThreshold` and `VerticalThreshold` property, to this component, as described in [AnchoredRegion](https://www.fluentui-blazor.net/AnchoredRegion). We will create a new PR for that.

This would avoid the display problem caused by the Status-bar taking up screen space and not being detected by **Popover**.

```xml
<FluentPopover Style="width: 300px;" VerticalThreshold="170" AnchorId="myPopoverButton" @bind-Open="_visible">
   ...
</FluentPopover>
```

https://github.com/microsoft/fluentui-blazor/assets/8350694/5c6fc7c9-c7ab-44be-a361-5f36159872f2


However, once the Popup is displayed on the screen, the rest of the screen cannot be moved. You must click outside the popup to close it.
To use a **Popup** independent of the rest of the page, there's the [AnchoredRegion](https://www.fluentui-blazor.net/AnchoredRegion) component, which we use for this Popover. **FluentAnchoredRegion** has many more configuration attributes.

**Comment by vnbaaij** [comment] 2024-01-27 09:14
Fixed with PR mentioned (by adding parameters to set threshold)

**Closed by vnbaaij** 2024-01-27 09:14 UTC
