### ISSUE TITLE
Blazor error when visiting fluentui-blazor.net

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#2589] opened 2024-08-28 09:10 UTC
I see the Blazor error bar in the UI:

![image](https://github.com/user-attachments/assets/a7c5bde6-4f54-4546-884c-4d41f97420f0)

And this in the console:

![image](https://github.com/user-attachments/assets/4842df35-ad10-4a09-9a10-f984a808da02)

**Comment by dvoituron** [comment] 2024-08-28 09:47
A page refresh should clear this error. 

This error is due to the JS execution order and will be corrected in the next major release.

**Comment by vnbaaij** [comment] 2024-08-28 09:55
@JamesNK confirmed a refresh fixed this. Closing...

**Closed by vnbaaij** 2024-08-28 09:55 UTC
Labels: triage

**Comment by JamesNK** [comment] 2024-08-28 13:49
Perhaps you should make caching less aggressive. Or serve content from a new path after deployment.

**Comment by coderdnewbie** [comment] 2024-09-06 07:19
The new .Net 9 static assets feature should help with this issue.

**Comment by JamesNK** [comment] 2024-09-06 07:51
When I go back and visit fluentui-blazor.net again, I get the same error:

![image](https://github.com/user-attachments/assets/c992341a-c75e-4aaa-b62f-8b3f2c67e8b3)

![image](https://github.com/user-attachments/assets/7f83be42-debb-4185-97ab-ca0eaf1ed675)

Again, refreshing fixes it. But I don't know why the error comes back.
