### ISSUE TITLE
fix: Unexpected behavior on parent click in Nested Menu

### ISSUE THREAD

**Issue by javadevil1982** [microsoft/fluentui-blazor#2206] opened 2024-06-18 09:04 UTC
# 🐛 Bug Report

I don't really know if it's a bug or a missing feature, but I find it very unusual that the whole menu closes when you click on the parent element in a nested menu.

## 🤔 Expected Behavior

When I click on an item with nested sub-items in a menu, I expect only the sub-menu to toggle between open and closed or just stay open. This is the usual behavior I know from MS Teams and all other applications.

![ParentClickClosesOnlySubMenu](https://github.com/microsoft/fluentui-blazor/assets/42235645/c1c1a34d-a43f-4705-991e-69343cbe388e)

## 😯 Current Behavior

Currently (version 4.8.0), clicking on an element with nested sub-elements in a menu closes the entire menu, which is very confusing for the user.

![ParentClickClosesAll](https://github.com/microsoft/fluentui-blazor/assets/42235645/9b56a68a-16af-45a6-b914-322e43e81bf1)

You can see and reproduce it with the code of the offical page https://www.fluentui-blazor.net/Menu#nested (see Nested).

## 💁 Possible Solution

If the behavior is incorrect, please correct it. If the behavior is wanted in some scenarios, please add a property that allows us to select the behavior.

## 🌍 Your Environment

* .NET 8.0 and Fluent UI Blazor library Version 4.8.0

**Comment by MarvinKlein1508** [comment] 2024-06-18 09:21
I think this has been addressed in https://github.com/microsoft/fluentui-blazor/pull/2183 already.

**Comment by vnbaaij** [comment] 2024-06-18 09:26
@javadevil1982 Can you include some screenshots/screengrabs/videos of what you are seeing and where. There are a lot of variants we are trying to cover and want to make sure we are talking about the same thing.

Tip: We use https://github.com/firatkiral/pypeek/ to create animated gifs of user interactions

**Comment by javadevil1982** [comment] 2024-06-18 09:31
@MarvinKlein1508  In the case of https://github.com/microsoft/fluentui-blazor/pull/2183 they fixed something in the FluentNavMenu, I mean the normal FluentMenu.

**Comment by vnbaaij** [comment] 2024-06-18 09:42
Oh sorry, I assumed you were talking about the NavMenu too...

There have not been any changes in the Menu and MenuItem components recently that changed this behavior. It has basically not changed since its inception.

Still, if you can provide a visual example **and reproduction code**, then we can assess if something can be changed/a parameter can be added/...

**Comment by javadevil1982** [comment] 2024-06-18 09:45
@vnbaaij, I added the screengrabs in my initial post.

**Comment by vnbaaij** [comment] 2024-06-23 16:30
This is just the behavior of the menu as it has been from the beginning.
As we merely wrap the web components for delivering these, I don't think we can change anything around this.

**Closed** 2024-06-23 16:31 UTC
Labels: status:needs-investigation, needs: repro code or repository
