### ISSUE TITLE
How to select the row that was selected before calling RefreshDataAsync

### ISSUE THREAD

**Issue by JarJasAskom** [microsoft/fluentui-blazor#2980] opened 2024-11-27 10:59 UTC
FluentDataGrid has Items property set to IQueryable returned by EF Core context. SelectMode is DataGridSelectMode.Single.

I select one row in the grid,  modify one value in the sql server table (using EF Core context) and call grid's RefreshDataAsync. FluentDataGrid shows the modified value but the selection is gone. 

How to restore selection? How to select row that was previously selected after calling RefreshDataAsync or how to force RefreshDataAsync not to change selection if after refresh selected record still exists?

I can't use @bind-SelectedItems because items are only inside FluentDataGrid. 

OnSelect/Property properties also does not help. After RefreshDataAsync Grid calls OnSelect with info that the record is now not selected.

**Comment by vnbaaij** [comment] 2024-11-27 11:23
We currently do not have anything in place to do that. Similar to #2842. Closing this as a duplicate of that

**Closed by vnbaaij** 2024-11-27 11:23 UTC
Labels: closed:duplicate
