### ISSUE TITLE
fix: FluentTreeView item null onSelectedItemChanged

### ISSUE THREAD

**Issue by mmaderic** [microsoft/fluentui-blazor#2926] opened 2024-11-12 19:24 UTC
# 🐛 Bug Report

With version 4.10.3, `FluentTreeView` no longer passes the selected item as an argument. The item is now always null in the `OnSelectAsync ` handler method.

## 💻 Repro or Code Sample

```
<FluentPopover AnchorId="@($"button-{Id}")" @bind-Open="IsSelectMode" AutoFocus="false" Style="height: fit-content; max-height: 500px; overflow-y: auto;">
    <Body>
        <FluentTreeView Items="@Items" LazyLoadItems="true" SelectedItemChanged="OnSelectAsync" SelectedItem="SelectedItem" />
    </Body>
</FluentPopover>
```

```
private Task OnSelectAsync(ITreeViewItem? item)
{
    var key = item?.Id;
    IsSelectMode = false;  

    return SetCurrentValueAsync(key);
}
```

## 🤔 Expected Behavior

The item shouldn't be null since the tree view contains and displays items correctly. 

## 🌍 Your Environment

* OS & Device: [Window 11]
* Browser [Microsoft Edge]
* .NET and Fluent UI Blazor library Version [NET 9 rc2, 4.10.3]

**Comment by vnbaaij** [comment] 2024-11-13 10:55
I can't run your reproduction code because it is incomplete...

Tested on 4.10,4 (next release) with this adapted sample code from the demo site:

```

<FluentTreeView Items="@Items" SelectedItem="@SelectedItem" LazyLoadItems="true" SelectedItemChanged="OnSelectAsync">
    <ItemTemplate>
        @context.Text
        <span style="color: var(--accent-fill-rest); margin: 0 4px;">
            @(context.Items == null ? "" : $"[{context.Items.Count()}]")
        </span>
    </ItemTemplate>
</FluentTreeView>

<div>
    <b>Total items:</b> @Count
</div>
<div>
    <b>Selected item:</b> @SelectedItem?.Text
</div>

@code
{
    bool IsSelectMode { get; set; }
    private ITreeViewItem? SelectedItem;

    private Icon IconCollapsed = new Icons.Regular.Size20.Folder();
    private Icon IconExpanded = new Icons.Regular.Size20.FolderOpen();

    private int Count = -1;
    private IEnumerable<ITreeViewItem>? Items = new List<ITreeViewItem>();

    protected override void OnInitialized()
    {
        Items = CreateTree(maxLevel: 5, maxItemsPerLevel: 12).Items;
        SelectedItem = Items?.ElementAt(3);
    }

    // Recursive method to create tree
    private TreeViewItem CreateTree(int maxLevel, int maxItemsPerLevel, int level = 0)
    {
        Count++;

        int nbItems = Random.Shared.Next(maxItemsPerLevel - 3, maxItemsPerLevel);

        var treeItem = new TreeViewItem
            {
                Text = $"Item {Count}",
                Disabled = level >= 2 && Count % 7 == 0,
                IconCollapsed = IconCollapsed,
                IconExpanded = IconExpanded,
                Expanded = level >= 2 && Count % 5 == 0,
                Items = level == maxLevel
                                  ? null
                                  : new List<TreeViewItem>(Enumerable.Range(1, nbItems)
                                                                     .Select(i => CreateTree(maxLevel, maxItemsPerLevel, level + 1))),
            };

        return treeItem;
    }

    private Task OnSelectAsync(ITreeViewItem? item)
    {
        SelectedItem = item;
        var key = item?.Id;
        IsSelectMode = false;

        return Task.CompletedTask; //SetCurrentValueAsync(key);
    }
}
```

The `SelectedItem` tracks the seelecteditem in the tree. Value passed into `OnSelectAsync` is**not ** `null`. Closing this as not (or no longer) reproducible.

**Closed by vnbaaij** 2024-11-13 10:55 UTC
Labels: Not reproducible
