### ISSUE TITLE
feat: add an indication of child items when NavMenu is collapsed

### ISSUE THREAD

**Issue by AlthalusDGr8** [microsoft/fluentui-blazor#1528] opened 2024-02-17 00:26 UTC
# 🙋 Feature Request
 Show menu items at level 2 and 2 when nav menu is collapsed

## 🤔 Expected Behavior

Show an icon that indicates there are sub items under a nav menu item when the nav menu is collapsed

## 😯 Current Behavior

Currently nothing happens when you press on a nav menu items that has children and it is collapsed

## 💁 Possible Solution

Either show the first few letters or icons of the children items or else pop over the items on top of the current menu
## 🔦 Context
When webpage is viewed inside a mobile view to gain some space users are collapsing the menu, however once there they cannot access the child links

## 💻 Examples
Example when non collapsed
<img width="155" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/13330897/83a270e8-c38a-46a4-9f87-af4286452d0e">

Example when collapsed
<img width="55" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/13330897/dd20c53d-03bf-472f-bd5d-b53db5896fab">

This can be tested live on https://dreamerscode.azurewebsites.net/

**Comment by vnbaaij** [comment] 2024-02-17 08:05
Hi,

This behavior is by design. The NavMenu should expand if you click on an item and then you can see if there are child items.

I can't see your issue on the example site you posted because the NavMenu does not have a Collapsible parameter set to true.

**Comment by vnbaaij** [comment] 2024-02-17 17:11
But they're is still something wrong in your site. Home always stays selected.

**Comment by AlthalusDGr8** [comment] 2024-02-18 09:12
not doing anything special.  This is my MianLayout.Blazor

`@inherits LayoutComponentBase

<FluentLayout Style="margin-top: 10px;">
    <FluentHeader>
        <FluentLabel Typo="Typography.Header">DreamersCode</FluentLabel>
    </FluentHeader>

    <FluentStack Orientation="Orientation.Horizontal">        
            <FluentNavMenu Width="200" Collapsible="true">
                <FluentNavLink Icon="@(new Icons.Regular.Size20.Home())" Href="/"></FluentNavLink>                
                <FluentNavGroup Title="Projects" Icon="@(new Icons.Regular.Size20.AppFolder())" Href="/projects">
                <FluentNavLink Icon="@(new Icons.Regular.Size20.BoxMultipleArrowRight())" Href="/projects/released">Released</FluentNavLink>
                <FluentNavLink Icon="@(new Icons.Regular.Size20.BoxEdit())" Href="/projects/beta">Beta</FluentNavLink>
                <FluentNavLink Icon="@(new Icons.Regular.Size20.BoxDismiss())" Href="/projects/parked">Parked</FluentNavLink>
            </FluentNavGroup>
            <FluentNavLink Icon="@(new Icons.Regular.Size24.InprivateAccount())" Href="/privacy">Privacy</FluentNavLink>
            </FluentNavMenu>
        
            <FluentBodyContent Style="margin-bottom:10px; margin-top:10px; margin-left:5px; margin-right:15px;">
                <div style="display: flex; justify-content: center; align-items: center;"> 
                @Body
            </div>
            </FluentBodyContent>
        
    </FluentStack>
    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <FluentFooter>
        <i class="fa-solid fa-copyright"></i>&nbsp;&nbsp;@DateTime.Now.Year - DreamersCode
    </FluentFooter>
</FluentLayout>`

**Comment by vnbaaij** [comment] 2024-02-18 10:39
Ok, your 'home' navlink probably needs a Match parameter set.

As said, the way it works is by design. If your nav group has an href, using an overview page is the way to go. If it doesn't have an href, it should expand the whole menu when clicked on and subsequently show you the arrow on the right to expand/collapse the group menu.

A collapsed NavMenu is not meant to be used for showing the complete navigation. It is just a method to 'move it out of the way' and create more screen real estate for the app. If you need the navigation items, it should be expanded first (by app or manually).

**Comment by vnbaaij** [comment] 2024-02-19 08:45
Yes, that looks nice indeed. But we have no plans (and time) to change our current implementation.
We take PR's... 😉

**Comment by vnbaaij** [comment] 2024-02-19 08:46
Closing this one as no action is required /planned

**Closed** 2024-02-19 08:46 UTC
